nohup: ignoring input
Run time of job "duoxiancheng (trigger: cron[hour='9', minute='21', second='9'], next run at: 2020-10-24 09:21:09 CST)" was missed by 0:04:24.220931
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
程序运行的次数 6
休眠时间 385
休眠时间 18
休眠时间 207
休眠时间 982
休眠时间 595
休眠时间 979
休眠时间 952
休眠时间 877
休眠时间 409
这个是栏目id为2 的文章长度 112
运行次数统计 1
获取到的文章标题 周易取名的男宝宝名字
存在
运行次数统计 2
获取到的文章标题 流行的宝宝取名 姓崔的宝宝起名的名字大全
存在
运行次数统计 3
获取到的文章标题 姓名打分 霸气男孩名字肖
存在
运行次数统计 4
获取到的文章标题 起名网的特色男孩名字肖
存在
运行次数统计 5
获取到的文章标题 好听的宝宝名字 男孩名字-姓萧的宝宝起名大全
存在
运行次数统计 6
获取到的文章标题 怎样起好名——陆姓男宝宝的名字
存在
运行次数统计 7
获取到的文章标题 值得推荐的起名之女宝宝名陆该怎么取名
存在
运行次数统计 8
获取到的文章标题 大数据取名，用五个元素为男孩命名唐
存在
运行次数统计 9
获取到的文章标题 免费八字取名 男孩的名字
存在
运行次数统计 10
获取到的文章标题 起名网的男孩的名字
存在
运行次数统计 11
获取到的文章标题 自动起名，如何在的猪年中给姓男孩的男孩命名
存在
运行次数统计 12
获取到的文章标题 大数据取名的最新发布的仲姓男宝宝的名字
存在
运行次数统计 13
获取到的文章标题 怎样取好名——隐姓赵男孩的名字
存在
运行次数统计 14
获取到的文章标题 科学起名 姓赵的男孩
存在
运行次数统计 15
获取到的文章标题 八字取名 男孩名字
存在
运行次数统计 16
获取到的文章标题 高分起名之命名赵某男孩的方法简介
存在
运行次数统计 17
获取到的文章标题 生辰八字取名，五元素缺乏金熊姓男宝宝的名字
存在
运行次数统计 18
获取到的文章标题 姓名打分——五元素缺乏金熊姓女宝宝
存在
运行次数统计 19
获取到的文章标题 科学取名 五元素缺乏金熊姓宝宝两个字符命名
存在
运行次数统计 20
获取到的文章标题 大数据起名，熊女宝宝名字推荐
存在
运行次数统计 21
获取到的文章标题 取名网之熊宝宝名字推荐
存在
运行次数统计 22
获取到的文章标题 楚辞取名——如何命名男女宝宝
不存在
随机生成的作者是 满德曜
随机生成的阅读数是 1060
获得的当前发布时间 2020-10-24 09:21:34
这个是栏目id为3 的文章长度 6
运行次数统计 1
获取到的文章标题 小孩起名——康熙字典中令人困惑的单词
存在
运行次数统计 2
获取到的文章标题 起名网的康熙字典中女宝宝的名字
不存在
随机生成的作者是 宋鸿远
随机生成的阅读数是 1541
获得的当前发布时间 2020-10-24 09:24:36
这个是栏目id为1 的文章长度 34
运行次数统计 1
获取到的文章标题 取名网——适合杨的宝宝名字的完整列表
存在
运行次数统计 2
获取到的文章标题 流年取名 如何获得周姓的好名字
存在
运行次数统计 3
获取到的文章标题 八字取名 周宝宝的名字是什么意思
存在
运行次数统计 4
获取到的文章标题 古诗词起名之如何给陈姓的宝宝起个霸气的名字
存在
运行次数统计 5
获取到的文章标题 起名技巧之西式宝宝名字陈
不存在
随机生成的作者是 熊乐咏
随机生成的阅读数是 3300
获得的当前发布时间 2020-10-24 09:27:34
这个是栏目id为3 的文章长度 28
运行次数统计 1
获取到的文章标题 国学起名，老鼠女郎意为好绰号
存在
运行次数统计 2
获取到的文章标题 楚辞起名 老鼠男孩有个好昵称
存在
运行次数统计 3
获取到的文章标题 最完美的起名 2020年的老鼠男孩的名字
存在
运行次数统计 4
获取到的文章标题 名字大全之2020年男孩外国和新潮英语昵称
存在
运行次数统计 5
获取到的文章标题 100分起名大全 昵称的老鼠男孩
存在
运行次数统计 6
获取到的文章标题 新生儿起名 2020RatBoy时尚西方昵称
不存在
随机生成的作者是 广文成
随机生成的阅读数是 3630
获得的当前发布时间 2020-10-24 09:27:58
这个是栏目id为3 的文章长度 67
运行次数统计 1
获取到的文章标题 八字取名——姓陈的女孩的唯一名字
存在
运行次数统计 2
获取到的文章标题 国学起名之女孩的西方名字，带有Mu字符
存在
运行次数统计 3
获取到的文章标题 楚辞取名之漂亮的女孩名字重叠
存在
运行次数统计 4
获取到的文章标题 姓名打分之2020RatGirl时髦名字
存在
运行次数统计 5
获取到的文章标题 100分起名大全的女孩的独特和罕见的重复名称
存在
运行次数统计 6
获取到的文章标题 姓名打分 优雅而富有诗意的四个字符的女孩的名字
不存在
随机生成的作者是 蒯元凯
随机生成的阅读数是 3559
获得的当前发布时间 2020-10-24 09:31:05
这个是栏目id为3 的文章长度 13
运行次数统计 1
获取到的文章标题 周易取名 ，名为猪的朱小女叫大全
存在
运行次数统计 2
获取到的文章标题 楚辞起名的可爱的小宝贝猪名字与陈
存在
运行次数统计 3
获取到的文章标题 在线取名 陈小猪的好名字
不存在
随机生成的作者是 秦明远
随机生成的阅读数是 2852
获得的当前发布时间 2020-10-24 09:35:46
这个是栏目id为3 的文章长度 31
运行次数统计 1
获取到的文章标题 如何利用八字起名——周易八字五元的命名方法和技巧
存在
运行次数统计 2
获取到的文章标题 姓名打分，命名出生的孙子时要注意的事项
存在
运行次数统计 3
获取到的文章标题 起名网，父母给孩子命名时要注意什么
存在
运行次数统计 4
获取到的文章标题 免费的宝宝取名的命名出生的女孩时要注意的事项
存在
运行次数统计 5
获取到的文章标题 新生儿取名，根据单词的结构开始命名时要注意的事项
存在
运行次数统计 6
获取到的文章标题 在线取名的如何使用具有草书前缀的单词命名双胞胎
不存在
随机生成的作者是 仰建义
随机生成的阅读数是 2954
获得的当前发布时间 2020-10-24 09:37:02
这个是栏目id为3 的文章长度 13
运行次数统计 1
获取到的文章标题 大数据取名 五元素缺乏金的宝宝名字
存在
运行次数统计 2
获取到的文章标题 100分起名大全——禁忌语中的五个要素命名
不存在
随机生成的作者是 红俊智
随机生成的阅读数是 1461
获得的当前发布时间 2020-10-24 09:37:28
这个是栏目id为3 的文章长度 57
运行次数统计 1
获取到的文章标题 小孩起名之文学典故中的宝宝名字常用词
存在
运行次数统计 2
获取到的文章标题 取名技巧，NalanCi的宝宝取名技巧
存在
运行次数统计 3
获取到的文章标题 科学起名，纳兰慈的宝宝名字的完整列表
存在
运行次数统计 4
获取到的文章标题 名字大全的一个姓黄的男孩的两个字符的好名字
存在
运行次数统计 5
获取到的文章标题 小孩取名的刘是这个男孩的好名字
存在
运行次数统计 6
获取到的文章标题 免费的宝宝起名的杨姓儿童的简单字母名字
存在
运行次数统计 7
获取到的文章标题 值得推荐的起名 姓黄的男孩的三个字符的好名字
存在
运行次数统计 8
获取到的文章标题 免费八字取名的他是一个男孩的有意义的名字
存在
运行次数统计 9
获取到的文章标题 免费八字取名——李是男孩的一个稀有和寓意的名字
存在
运行次数统计 10
获取到的文章标题 新生儿如何起名 2020年给张姓男孩的好名字
存在
运行次数统计 11
获取到的文章标题Exception in thread lanmu_id_1:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "fabu0923.py", line 40, in lanmu_id_1
    xieru_zong = Article_zan.query.filter(Article_zan.lanmu_id == 1).all()[changdu]
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3341, in all
    return list(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3525, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3540, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3518, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
    execution_options=execution_options,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
    engine, execution_options
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2305, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2343, in _wrap_pool_connect
    e, dialect, self
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1585, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: http://sqlalche.me/e/13/e3q8)

Exception in thread lanmu_id_4:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "fabu0923.py", line 186, in lanmu_id_4
    xieru_zong = Article_zan.query.filter(Article_zan.lanmu_id == 4).all()[changdu]
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3341, in all
    return list(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3525, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3540, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3518, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
    execution_options=execution_options,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
    engine, execution_options
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2305, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2343, in _wrap_pool_connect
    e, dialect, self
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1585, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: http://sqlalche.me/e/13/e3q8)

Exception in thread lanmu_id_2:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 691, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "/usr/local/python3/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 1082, in read
    self._read_result_packet(first_packet)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 1152, in _read_result_packet
    self._read_rowdata_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 1186, in _read_rowdata_packet
    packet = self.connection._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 674, in _read_packet
    recv_data = self._read_bytes(bytes_to_read)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 699, in _read_bytes
    "Lost connection to MySQL server during query (%s)" % (e,))
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query ([Errno 104] Connection reset by peer)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "fabu0923.py", line 90, in lanmu_id_2
    xieru_zong = Article_zan.query.filter(Article_zan.lanmu_id == 2).all()[changdu]
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3341, in all
    return list(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3528, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1133, in _execute_clauseelement
    distilled_params,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1318, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1512, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 1082, in read
    self._read_result_packet(first_packet)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 1152, in _read_result_packet
    self._read_rowdata_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 1186, in _read_rowdata_packet
    packet = self.connection._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 674, in _read_packet
    recv_data = self._read_bytes(bytes_to_read)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 699, in _read_bytes
    "Lost connection to MySQL server during query (%s)" % (e,))
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query ([Errno 104] Connection reset by peer)')
[SQL: SELECT article_zan.id AS article_zan_id, article_zan.title AS article_zan_title, article_zan.content AS article_zan_content, article_zan.description AS article_zan_description, article_zan.zaiyao AS article_zan_zaiyao, article_zan.lanmu_id AS article_zan_lanmu_id, article_zan.author_name AS article_zan_author_name, article_zan.article_yuedu AS article_zan_article_yuedu, article_zan.article_time AS article_zan_article_time 
FROM article_zan 
WHERE article_zan.lanmu_id = %(lanmu_id_1)s]
[parameters: {'lanmu_id_1': 2}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

Exception in thread lanmu_id_7:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 500, in checkout
    rec._checkin_failed(err)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 497, in checkout
    dbapi_connection = rec.get_connection()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 610, in get_connection
    self.__connect()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "fabu0923.py", line 333, in lanmu_id_7
    xieru_zong = Article_zan.query.filter(Article_zan.lanmu_id == 7).all()[changdu]
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3341, in all
    return list(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3525, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3540, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3518, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
    execution_options=execution_options,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
    engine, execution_options
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2305, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2343, in _wrap_pool_connect
    e, dialect, self
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1585, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 500, in checkout
    rec._checkin_failed(err)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 497, in checkout
    dbapi_connection = rec.get_connection()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 610, in get_connection
    self.__connect()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: http://sqlalche.me/e/13/e3q8)

Exception in thread lanmu_id_5:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 500, in checkout
    rec._checkin_failed(err)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 497, in checkout
    dbapi_connection = rec.get_connection()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 610, in get_connection
    self.__connect()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "fabu0923.py", line 235, in lanmu_id_5
    xieru_zong = Article_zan.query.filter(Article_zan.lanmu_id == 5).all()[changdu]
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3341, in all
    return list(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3525, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3540, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3518, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
    execution_options=execution_options,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
    engine, execution_options
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2305, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2343, in _wrap_pool_connect
    e, dialect, self
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1585, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 500, in checkout
    rec._checkin_failed(err)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 497, in checkout
    dbapi_connection = rec.get_connection()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 610, in get_connection
    self.__connect()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: http://sqlalche.me/e/13/e3q8)

Exception in thread lanmu_id_9:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 500, in checkout
    rec._checkin_failed(err)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 497, in checkout
    dbapi_connection = rec.get_connection()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 610, in get_connection
    self.__connect()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "fabu0923.py", line 431, in lanmu_id_9
    xieru_zong = Article_zan.query.filter(Article_zan.lanmu_id == 9).all()[changdu]
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3341, in all
    return list(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3525, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3540, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3518, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
    execution_options=execution_options,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
    engine, execution_options
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2305, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2343, in _wrap_pool_connect
    e, dialect, self
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1585, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 500, in checkout
    rec._checkin_failed(err)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 497, in checkout
    dbapi_connection = rec.get_connection()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 610, in get_connection
    self.__connect()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: http://sqlalche.me/e/13/e3q8)
nohup: ignoring input
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
程序运行的次数 7
休眠时间 250
休眠时间 688
休眠时间 759
休眠时间 23
休眠时间 12
休眠时间 375
休眠时间 706
休眠时间 281
休眠时间 512
这个是栏目id为3 的文章长度 72
运行次数统计 1
获取到的文章标题 姓名打分 优雅而富有诗意的四个字符的女孩的名字
存在
运行次数统计 2
获取到的文章标题 流年起名，好仙女的名字
存在
运行次数统计 3
获取到的文章标题 宝宝怎么取名，甜美美丽的女孩重复的名字
存在
运行次数统计 4
获取到的文章标题 古诗词取名，漂亮优雅的女孩名字
存在
运行次数统计 5
获取到的文章标题 高分起名之西方和时髦女孩的名字
存在
运行次数统计 6
获取到的文章标题 自动起名之童话女孩的重复名称
不存在
随机生成的作者是 越俊达
随机生成的阅读数是 3813
获得的当前发布时间 2020-10-25 09:21:22
这个是栏目id为3 的文章长度 62
运行次数统计 1
获取到的文章标题 免费的宝宝起名的杨姓儿童的简单字母名字
存在
运行次数统计 2
获取到的文章标题 值得推荐的起名 姓黄的男孩的三个字符的好名字
存在
运行次数统计 3
获取到的文章标题 免费八字取名的他是一个男孩的有意义的名字
存在
运行次数统计 4
获取到的文章标题 免费八字取名——李是男孩的一个稀有和寓意的名字
存在
运行次数统计 5
获取到的文章标题 新生儿如何起名 2020年给张姓男孩的好名字
存在
运行次数统计 6
获取到的文章标题 最完美的起名——暗示李姓男孩的一个字母的名字
存在
运行次数统计 7
获取到的文章标题 科学起名之鼠年里新的和独特的男孩名字
存在
运行次数统计 8
获取到的文章标题 楚辞取名 敏感人物男孩的好名字
存在
运行次数统计 9
获取到的文章标题 流年起名的不错的男孩名字
存在
运行次数统计 10
获取到的文章标题 起名技巧之好男孩名字与风景
存在
运行次数统计 11
获取到的文章标题 如何利用八字起名，高贵霸气的古代男孩的名字
不存在
随机生成的作者是 咸志诚
随机生成的阅读数是 1056
获得的当前发布时间 2020-10-25 09:21:33
这个是栏目id为1 的文章长度 36
运行次数统计 1
获取到的文章标题 八字取名 周宝宝的名字是什么意思
存在
运行次数统计 2
获取到的文章标题 古诗词起名之如何给陈姓的宝宝起个霸气的名字
存在
运行次数统计 3
获取到的文章标题 起名技巧之西式宝宝名字陈
存在
运行次数统计 4
获取到的文章标题 免费的宝宝起名——陈怡的宝宝名字
存在
运行次数统计 5
获取到的文章标题 流年起名之别致的宝宝名字
不存在
随机生成的作者是 于新荣
随机生成的阅读数是 2576
获得的当前发布时间 2020-10-25 09:25:19
这个是栏目id为3 的文章长度 15
运行次数统计 1
获取到的文章标题 在线取名 陈小猪的好名字
存在
运行次数统计 2
获取到的文章标题 楚辞起名之最新的宝宝名字
存在
运行次数统计 3
获取到的文章标题 大数据起名，非凡的小猪名字
不存在
随机生成的作者是 周玉堂
随机生成的阅读数是 2303
获得的当前发布时间 2020-10-25 09:25:50
这个是栏目id为3 的文章长度 15
运行次数统计 1
获取到的文章标题 100分起名大全之这五个要素是木制宝宝的名字
存在
运行次数统计 2
获取到的文章标题 大数据起名的如何基于五个要素的力量给宝宝起名
不存在
随机生成的作者是 沃彬彬
随机生成的阅读数是 2994
获得的当前发布时间 2020-10-25 09:27:24
这个是栏目id为3 的文章长度 30
运行次数统计 1
获取到的文章标题 最完美的起名 2020年的老鼠男孩的名字
存在
运行次数统计 2
获取到的文章标题 名字大全之2020年男孩外国和新潮英语昵称
存在
运行次数统计 3
获取到的文章标题 100分起名大全 昵称的老鼠男孩
存在
运行次数统计 4
获取到的文章标题 新生儿起名 2020RatBoy时尚西方昵称
存在
运行次数统计 5
获取到的文章标题 怎样取好名之漂亮而有意义的宝宝名字
存在
运行次数统计 6
获取到的文章标题 好听的宝宝名字之简单文艺女郎的昵称
不存在
随机生成的作者是 敖黎昕
随机生成的阅读数是 1839
获得的当前发布时间 2020-10-25 09:29:41
这个是栏目id为2 的文章长度 118
运行次数统计 1
获取到的文章标题 值得推荐的起名之女宝宝名陆该怎么取名
存在
运行次数统计 2
获取到的文章标题 大数据取名，用五个元素为男孩命名唐
存在
运行次数统计 3
获取到的文章标题 免费八字取名 男孩的名字
存在
运行次数统计 4
获取到的文章标题 起名网的男孩的名字
存在
运行次数统计 5
获取到的文章标题 自动起名，如何在的猪年中给姓男孩的男孩命名
存在
运行次数统计 6
获取到的文章标题 大数据取名的最新发布的仲姓男宝宝的名字
存在
运行次数统计 7
获取到的文章标题 怎样取好名——隐姓赵男孩的名字
存在
运行次数统计 8
获取到的文章标题 科学起名 姓赵的男孩
存在
运行次数统计 9
获取到的文章标题 八字取名 男孩名字
存在
运行次数统计 10
获取到的文章标题 高分起名之命名赵某男孩的方法简介
存在
运行次数统计 11
获取到的文章标题 生辰八字取名，五元素缺乏金熊姓男宝宝的名字
存在
运行次数统计 12
获取到的文章标题 姓名打分——五元素缺乏金熊姓女宝宝
存在
运行次数统计 13
获取到的文章标题 科学取名 五元素缺乏金熊姓宝宝两个字符命名
存在
运行次数统计 14
获取到的文章标题 大数据起名，熊女宝宝名字推荐
存在
运行次数统计 15
获取到的文章标题 取名网之熊宝宝名字推荐
存在
运行次数统计 16
获取到的文章标题 楚辞取名——如何命名男女宝宝
存在
运行次数统计 17
获取到的文章标题 怎样取好名，宝宝姓黄三字名字
存在
运行次数统计 18
获取到的文章标题 免费的宝宝起名之宝宝姓黄有两个字符
存在
运行次数统计 19
获取到的文章标题 热门起名技巧 带梅姓男孩的好名字
存在
运行次数统计 20
获取到的文章标题 免费的宝宝取名——以梅姓为女孩命名的美丽名字
存在
运行次数统计 21
获取到的文章标题 取名网——姓盛的男孩的好名字
存在
运行次数统计 22
获取到的文章标题 好听的宝宝名字的姓盛的女孩的好名字
不存在
随机生成的作者是 冉安然
随机生成的阅读数是 1123
获得的当前发布时间 2020-10-25 09:32:44
这个是栏目id为3 的文章长度 33
运行次数统计 1
获取到的文章标题 起名网，父母给孩子命名时要注意什么
存在
运行次数统计 2
获取到的文章标题 免费的宝宝取名的命名出生的女孩时要注意的事项
存在
运行次数统计 3
获取到的文章标题 新生儿取名，根据单词的结构开始命名时要注意的事项
存在
运行次数统计 4
获取到的文章标题 在线取名的如何使用具有草书前缀的单词命名双胞胎
存在
运行次数统计 5
获取到的文章标题 免费的宝宝起名——在给宝宝命名时请注意这些事项
存在
运行次数统计 6
获取到的文章标题 免费的宝宝取名 如何正确命名新生宝宝
不存在
随机生成的作者是 方宏放
随机生成的阅读数是 1107
获得的当前发布时间 2020-10-25 09:32:56
这个是栏目id为3 的文章长度 7
运行次数统计 1
获取到的文章标题 起名网的康熙字典中女宝宝的名字
存在
运行次数统计 2
获取到的文章标题 八字取名之康熙字典中男宝宝的名字
不存在
随机生成的作者是 侯志学
随机生成的阅读数是 1072
获得的当前发布时间 2020-10-25 09:33:48
运行次数统计 7
获取到的文章标题 高分起名的漂亮纯正优雅的女孩名字
不存在
随机生成的作者是 满修德
随机生成的阅读数是 1601
获得的当前发布时间 2020-10-25 09:53:46
运行次数统计 12
获取到的文章标题 流年取名 林姓男孩有诗意的名字
不存在
随机生成的作者是 连才捷
随机生成的阅读数是 1154
获得的当前发布时间 2020-10-25 10:02:46
运行次数统计 3
获取到的文章标题 怎样起好名之生日字符命名技巧
不存在
随机生成的作者是 梁学博
随机生成的阅读数是 3802
获得的当前发布时间 2020-10-25 10:10:14
运行次数统计 23
获取到的文章标题 免费的宝宝起名 林姓男孩的好名字
不存在
随机生成的作者是 龙阳煦
随机生成的阅读数是 1567
获得的当前发布时间 2020-10-25 10:16:19
运行次数统计 8
获取到的文章标题 怎样起好名，杨与安的女孩名字
不存在
随机生成的作者是 钟君浩
随机生成的阅读数是 2362
获得的当前发布时间 2020-10-25 10:37:25
运行次数统计 13
获取到的文章标题 周易起名之男孩的名字对水有很好的意义
不存在
随机生成的作者是 慕英勋
随机生成的阅读数是 2105
获得的当前发布时间 2020-10-25 10:46:23
运行次数统计 7
获取到的文章标题 取名网——长者给孩子起名时应注意什么
不存在
随机生成的作者是 侯修谨
随机生成的阅读数是 1975
获得的当前发布时间 2020-10-25 10:49:00
运行次数统计 24
获取到的文章标题 八字取名，姓林的女孩的好名字
不存在
随机生成的作者是 鱼子民
随机生成的阅读数是 3618
获得的当前发布时间 2020-10-25 10:54:11
运行次数统计 9
获取到的文章标题 流年起名——一个叫杨的女孩的好名字
不存在
随机生成的作者是 李金鑫
随机生成的阅读数是 3709
获得的当前发布时间 2020-10-25 11:11:18
运行次数统计 6
获取到的文章标题 宝宝怎么取名——如何给刘姓宝宝起个好听的名字
不存在
随机生成的作者是 邓伟才
随机生成的阅读数是 1819
获得的当前发布时间 2020-10-25 11:16:01
运行次数统计 14
获取到的文章标题 周易取名，这个男孩的好名字
不存在
随机生成的作者是 林阳秋
随机生成的阅读数是 3182
获得的当前发布时间 2020-10-25 11:17:39
运行次数统计 25
获取到的文章标题 宝宝怎么取名之推荐给男孩的单词列表
不存在
随机生成的作者是 魏飞羽
随机生成的阅读数是 2765
获得的当前发布时间 2020-10-25 11:19:20
运行次数统计 10
获取到的文章标题 生辰八字起名——鼠年的女宝宝意味着好名字
不存在
随机生成的作者是 李金鑫
随机生成的阅读数是 1520
获得的当前发布时间 2020-10-25 11:44:02
运行次数统计 15
获取到的文章标题 科学取名之古典童话男孩的名字
不存在
随机生成的作者是 程飞驰
随机生成的阅读数是 2493
获得的当前发布时间 2020-10-25 11:57:22
运行次数统计 26
获取到的文章标题 起名技巧之老姓男宝宝三个字符的名字
不存在
随机生成的作者是 唐安国
随机生成的阅读数是 2507
获得的当前发布时间 2020-10-25 11:58:14
运行次数统计 8
获取到的文章标题 免费的宝宝取名的根据实际情况选择命名方式，以取好名
不存在
随机生成的作者是 邰天罡
随机生成的阅读数是 2772
获得的当前发布时间 2020-10-25 12:08:54
运行次数统计 11
获取到的文章标题 取名网——曾姓的女孩有一个很好的名字。
不存在
随机生成的作者是 周玉堂
随机生成的阅读数是 1876
获得的当前发布时间 2020-10-25 12:23:23
运行次数统计 16
获取到的文章标题 新生儿起名——男孩的正式名字
不存在
随机生成的作者是 广敏才
随机生成的阅读数是 1000
获得的当前发布时间 2020-10-25 12:34:27
运行次数统计 27
获取到的文章标题 流行的宝宝取名，男宝宝三个字符的名字荣
不存在
随机生成的作者是 乜弘新
随机生成的阅读数是 3086
获得的当前发布时间 2020-10-25 12:35:08
运行次数统计 28
获取到的文章标题 怎样起好名的荣姓男宝宝两个字母的名字
不存在
随机生成的作者是 蒯永元
随机生成的阅读数是 2825
获得的当前发布时间 2020-10-25 12:52:23
运行次数统计 7
获取到的文章标题 生辰八字取名的如何取悦刘易名
不存在
随机生成的作者是 赵元甲
随机生成的阅读数是 1457
获得的当前发布时间 2020-10-25 12:56:25
运行次数统计 17
获取到的文章标题 周易起名，别致优雅的男孩名字
不存在
随机生成的作者是 韩正谊
随机生成的阅读数是 1162
获得的当前发布时间 2020-10-25 13:04:59
运行次数统计 12
获取到的文章标题 起名技巧，老鼠女郎的雅致名字
不存在
随机生成的作者是 红承平
随机生成的阅读数是 1723
获得的当前发布时间 2020-10-25 13:07:24
运行次数统计 29
获取到的文章标题 流行的宝宝取名，姓氏男宝宝三个字符的名字
不存在
随机生成的作者是 毋修竹
随机生成的阅读数是 2179
获得的当前发布时间 2020-10-25 13:27:58
运行次数统计 18
获取到的文章标题 大数据起名——一个男孩的好名字，单词“jun”
不存在
随机生成的作者是 莘英哲
随机生成的阅读数是 1680
获得的当前发布时间 2020-10-25 13:38:55
运行次数统计 13
获取到的文章标题 楚辞起名——一个姓张的女孩，好听而稀有
不存在
随机生成的作者是 燕勇军
随机生成的阅读数是 1705
获得的当前发布时间 2020-10-25 13:49:58
运行次数统计 9
获取到的文章标题 流年起名，如何快速掌握新手的命名技巧，只需记住要点
不存在
随机生成的作者是 曹宇荫
随机生成的阅读数是 3686
获得的当前发布时间 2020-10-25 13:53:47
运行次数统计 30
获取到的文章标题 名字大全 姓氏男宝宝两个字符的名字
不存在
随机生成的作者是 那欣荣
随机生成的阅读数是 2652
获得的当前发布时间 2020-10-25 13:59:16
运行次数统计 19
获取到的文章标题 怎样取好名之王的优雅而霸气的名字
不存在
随机生成的作者是 史天工
随机生成的阅读数是 3299
获得的当前发布时间 2020-10-25 14:11:25
运行次数统计 8
获取到的文章标题 科学取名的宝宝李适合什么名字
不存在
随机生成的作者是 贡元武
随机生成的阅读数是 3867
获得的当前发布时间 2020-10-25 14:15:42
运行次数统计 14
获取到的文章标题 值得推荐的起名——姓陈的女孩名字好听
不存在
随机生成的作者是 惠嘉运
随机生成的阅读数是 1009
获得的当前发布时间 2020-10-25 14:27:22
运行次数统计 31
获取到的文章标题 在线取名——优雅的唐女孩名字
不存在
随机生成的作者是 殳才良
随机生成的阅读数是 2896
获得的当前发布时间 2020-10-25 14:40:10
运行次数统计 20
获取到的文章标题 免费的宝宝起名之杨的简单好听的名字
不存在
随机生成的作者是 宦修雅
随机生成的阅读数是 2933
获得的当前发布时间 2020-10-25 14:45:51
运行次数统计 15
获取到的文章标题 大数据取名之刘雅雅的名字
不存在
随机生成的作者是 仰建义
随机生成的阅读数是 1830
获得的当前发布时间 2020-10-25 15:08:10
运行次数统计 32
获取到的文章标题 大数据起名 男宝宝的名字
不存在
随机生成的作者是 桓宏义
随机生成的阅读数是 2818
获得的当前发布时间 2020-10-25 15:17:02
运行次数统计 10
获取到的文章标题 楚辞取名——如何确保您孩子的名字是杰出的和令人印象深刻的
不存在
随机生成的作者是 殳同化
随机生成的阅读数是Exception in thread lanmu_id_9:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 500, in checkout
    rec._checkin_failed(err)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 497, in checkout
    dbapi_connection = rec.get_connection()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 638, in get_connection
    self.__connect()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "fabu0923.py", line 431, in lanmu_id_9
    xieru_zong = Article_zan.query.filter(Article_zan.lanmu_id == 9).all()[changdu]
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3341, in all
    return list(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3525, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3540, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3518, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
    execution_options=execution_options,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
    engine, execution_options
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2305, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2343, in _wrap_pool_connect
    e, dialect, self
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1585, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 500, in checkout
    rec._checkin_failed(err)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 497, in checkout
    dbapi_connection = rec.get_connection()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 638, in get_connection
    self.__connect()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: http://sqlalche.me/e/13/e3q8)

Job "duoxiancheng (trigger: cron[hour='9', minute='21', second='9'], next run at: 2020-10-26 09:21:09 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 713, in _write_bytes
    self._sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 771, in _execute_command
    self._write_bytes(packet)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 718, in _write_bytes
    "MySQL server has gone away (%r)" % (e,))
pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "fabu0923.py", line 509, in duoxiancheng
    db.session.commit()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2523, in flush
    self._flush(objects)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2624, in _flush
    flush_context.execute()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    statement, params
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1133, in _execute_clauseelement
    distilled_params,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1318, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1512, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 771, in _execute_command
    self._write_bytes(packet)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 718, in _write_bytes
    "MySQL server has gone away (%r)" % (e,))
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
[SQL: INSERT INTO cishu (cishu) VALUES (%(cishu)s)]
[parameters: {'cishu': 6}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
 2442
获得的当前发布时间 2020-10-25 15:20:10
运行次数统计 33
获取到的文章标题 八字取名之漂亮的单字符钟姓男孩
不存在
随机生成的作者是 巢鸿朗
随机生成的阅读数是 2660
获得的当前发布时间 2020-10-25 15:46:56
运行次数统计 9
获取到的文章标题 新生儿起名，李贝宝宝叫什么名字？
不存在
随机生成的作者是 从元纬
随机生成的阅读数是 3462
获得的当前发布时间 2020-10-25 16:14:31
运行次数统计 34
获取到的文章标题 新生儿取名的气氛很好
不存在
随机生成的作者是 蒯永元
随机生成的阅读数是 1912
获得的当前发布时间 2020-10-25 16:25:45
运行次数统计 4
获取到的文章标题 大数据起名的熙非常好的宝宝名字
不存在
随机生成的作者是 公承教
随机生成的阅读数是 2225
获得的当前发布时间 2020-10-25 16:38:09
运行次数统计 35
获取到的文章标题 自动起名之梦想出差意味着什么
不存在
随机生成的作者是 卢俊语
随机生成的阅读数是 2258
获得的当前发布时间 2020-10-25 16:51:24
运行次数统计 36
获取到的文章标题 科学取名，姓霍的女孩的好名字
不存在
随机生成的作者是 束博赡
随机生成的阅读数是 3079
获得的当前发布时间 2020-10-25 17:30:59
运行次数统计 37
获取到的文章标题 流行的宝宝取名的猪年刘姓
不存在
随机生成的作者是 郑凯泽
随机生成的阅读数是 3907
获得的当前发布时间 2020-10-25 18:10:29
运行次数统计 38
获取到的文章标题 流行的宝宝取名，猪年男孩叫吴的名字
不存在
随机生成的作者是 梁嘉珍
随机生成的阅读数是 3373
获得的当前发布时间 2020-10-25 18:38:20
运行次数统计 39
获取到的文章标题 起名网 特色宝宝名字
不存在
随机生成的作者是 唐安国
随机生成的阅读数是 2204
获得的当前发布时间 2020-10-25 19:12:46
运行次数统计 40
获取到的文章标题 大数据取名的很好听王的男孩名字
不存在
随机生成的作者是 须正真
随机生成的阅读数是 2397
获得的当前发布时间 2020-10-25 19:45:38
运行次数统计 41
获取到的文章标题 起名需要注意什么 男宝宝名字郑
不存在
随机生成的作者是 古正阳
随机生成的阅读数是 1948
获得的当前发布时间 2020-10-25 20:12:25
运行次数统计 7
获取到的文章标题 流年取名的稻米小子的老鼠男孩
不存在
随机生成的作者是 范懿轩
随机生成的阅读数是 1286
获得的当前发布时间 2020-10-25 22:19:24
运行次数统计 8
主线程结束
程序运行的次数 7
休眠时间 370
休眠时间 87
休眠时间 187
休眠时间 311
休眠时间 398
休眠时间 894
休眠时间 793
休眠时间 740
休眠时间 665
这个是栏目id为2 的文章长度 138
运行次数统计 1
获取到的文章标题 取名网——姓盛的男孩的好名字
存在
运行次数统计 2
获取到的文章标题 好听的宝宝名字的姓盛的女孩的好名字
存在
运行次数统计 3
获取到的文章标题 免费的宝宝起名 林姓男孩的好名字
存在
运行次数统计 4
获取到的文章标题 八字取名，姓林的女孩的好名字
存在
运行次数统计 5
获取到的文章标题 宝宝怎么取名之推荐给男孩的单词列表
存在
运行次数统计 6
获取到的文章标题 起名技巧之老姓男宝宝三个字符的名字
存在
运行次数统计 7
获取到的文章标题 流行的宝宝取名，男宝宝三个字符的名字荣
存在
运行次数统计 8
获取到的文章标题 怎样起好名的荣姓男宝宝两个字母的名字
存在
运行次数统计 9
获取到的文章标题 流行的宝宝取名，姓氏男宝宝三个字符的名字
存在
运行次数统计 10
获取到的文章标题 名字大全 姓氏男宝宝两个字符的名字
存在
运行次数统计 11
获取到的文章标题 在线取名——优雅的唐女孩名字
存在
运行次数统计 12
获取到的文章标题 大数据起名 男宝宝的名字
存在
运行次数统计 13
获取到的文章标题 八字取名之漂亮的单字符钟姓男孩
存在
运行次数统计 14
获取到的文章标题 新生儿取名的气氛很好
存在
运行次数统计 15
获取到的文章标题 自动起名之梦想出差意味着什么
存在
运行次数统计 16
获取到的文章标题 科学取名，姓霍的女孩的好名字
存在
运行次数统计 17
获取到的文章标题 流行的宝宝取名的猪年刘姓
存在
运行次数统计 18
获取到的文章标题 流行的宝宝取名，猪年男孩叫吴的名字
存在
运行次数统计 19
获取到的文章标题 起名网 特色宝宝名字
存在
运行次数统计 20
获取到的文章标题 大数据取名的很好听王的男孩名字
存在
运行次数统计 21
获取到的文章标题 起名需要注意什么 男宝宝名字郑
存在
运行次数统计 22
获取到的文章标题 好听的宝宝名字之郑姓女宝宝
不存在
随机生成的作者是 红承平
随机生成的阅读数是 3444
获得的当前发布时间 2020-10-26 09:22:42
这个是栏目id为3 的文章长度 8
运行次数统计 1
获取到的文章标题 八字取名之康熙字典中男宝宝的名字
存在
运行次数统计 2
获取到的文章标题 起名技巧 康熙字典命名技巧
不存在
随机生成的作者是 冯昊昊
随机生成的阅读数是 1063
获得的当前发布时间 2020-10-26 09:24:16
这个是栏目id为3 的文章长度 72
运行次数统计 1
获取到的文章标题 如何利用八字起名，高贵霸气的古代男孩的名字
存在
运行次数统计 2
获取到的文章标题 流年取名 林姓男孩有诗意的名字
存在
运行次数统计 3
获取到的文章标题 周易起名之男孩的名字对水有很好的意义
存在
运行次数统计 4
获取到的文章标题 周易取名，这个男孩的好名字
存在
运行次数统计 5
获取到的文章标题 科学取名之古典童话男孩的名字
存在
运行次数统计 6
获取到的文章标题 新生儿起名——男孩的正式名字
存在
运行次数统计 7
获取到的文章标题 周易起名，别致优雅的男孩名字
存在
运行次数统计 8
获取到的文章标题 大数据起名——一个男孩的好名字，单词“jun”
存在
运行次数统计 9
获取到的文章标题 怎样取好名之王的优雅而霸气的名字
存在
运行次数统计 10
获取到的文章标题 免费的宝宝起名之杨的简单好听的名字
存在
运行次数统计 11
获取到的文章标题 起名网的最适合老鼠男孩的好名字
不存在
随机生成的作者是 阴乐天
随机生成的阅读数是 2283
获得的当前发布时间 2020-10-26 09:26:21
这个是栏目id为1 的文章长度 41
运行次数统计 1
获取到的文章标题 宝宝怎么取名——如何给刘姓宝宝起个好听的名字
存在
运行次数统计 2
获取到的文章标题 生辰八字取名的如何取悦刘易名
存在
运行次数统计 3
获取到的文章标题 科学取名的宝宝李适合什么名字
存在
运行次数统计 4
获取到的文章标题 新生儿起名，李贝宝宝叫什么名字？
存在
运行次数统计 5
获取到的文章标题 小孩起名，如何给张姓宝宝起好名字
不存在
随机生成的作者是 蔡俊逸
随机生成的阅读数是 1761
获得的当前发布时间 2020-10-26 09:27:19
这个是栏目id为3 的文章长度 82
运行次数统计 1
获取到的文章标题 取名网——曾姓的女孩有一个很好的名字。
存在
运行次数统计 2
获取到的文章标题 起名技巧，老鼠女郎的雅致名字
存在
运行次数统计 3
获取到的文章标题 楚辞起名——一个姓张的女孩，好听而稀有
存在
运行次数统计 4
获取到的文章标题 值得推荐的起名——姓陈的女孩名字好听
存在
运行次数统计 5
获取到的文章标题 大数据取名之刘雅雅的名字
存在
运行次数统计 6
获取到的文章标题 古诗词起名的姓李的女孩，名字旁边有金子
不存在
随机生成的作者是 蓟华清
随机生成的阅读数是 3555
获得的当前发布时间 2020-10-26 09:27:47
这个是栏目id为3 的文章长度 32
运行次数统计 1
获取到的文章标题 100分起名大全 昵称的老鼠男孩
存在
运行次数统计 2
获取到的文章标题 新生儿起名 2020RatBoy时尚西方昵称
存在
运行次数统计 3
获取到的文章标题 怎样取好名之漂亮而有意义的宝宝名字
存在
运行次数统计 4
获取到的文章标题 好听的宝宝名字之简单文艺女郎的昵称
存在
运行次数统计 5
获取到的文章标题 流年取名的稻米小子的老鼠男孩
存在
运行次数统计 6
获取到的文章标题 科学起名之昵称
不存在
随机生成的作者是 高意蕴
随机生成的阅读数是 2419
获得的当前发布时间 2020-10-26 09:32:14
这个是栏目id为3 的文章长度 17
运行次数统计 1
获取到的文章标题 大数据起名，非凡的小猪名字
存在
运行次数统计 2
获取到的文章标题 大数据起名的熙非常好的宝宝名字
存在
运行次数统计 3
获取到的文章标题 小孩取名——喜宝宝的好名字
不存在
随机生成的作者是 谷宏恺
随机生成的阅读数是 3249
获得的当前发布时间 2020-10-26 09:33:29
这个是栏目id为3 的文章长度 38
运行次数统计 1
获取到的文章标题 免费的宝宝取名 如何正确命名新生宝宝
存在
运行次数统计 2
获取到的文章标题 取名网——长者给孩子起名时应注意什么
存在
运行次数统计 3
获取到的文章标题 免费的宝宝取名的根据实际情况选择命名方式，以取好名
存在
运行次数统计 4
获取到的文章标题 流年起名，如何快速掌握新手的命名技巧，只需记住要点
存在
运行次数统计 5
获取到的文章标题 楚辞取名——如何确保您孩子的名字是杰出的和令人印象深刻的
存在
运行次数统计 6
获取到的文章标题 高分起名之为有普通姓氏的孩子选择什么单词
不存在
随机生成的作者是 周玉堂
随机生成的阅读数是 1792
获得的当前发布时间 2020-10-26 09:34:23
这个是栏目id为3 的文章长度 17
运行次数统计 1
获取到的文章标题 怎样起好名之生日字符命名技巧
存在
运行次数统计 2
获取到的文章标题 免费的宝宝起名——金宝贝名字
不存在
随机生成的作者是 鱼刚毅
随机生成的阅读数是 2249
获得的当前发布时间 2020-10-26 09:36:03
运行次数统计 23
获取到的文章标题 免费的宝宝取名，宝宝姓李
不存在
随机生成的作者是 祖自怡
随机生成的阅读数是 1302
获得的当前发布时间 2020-10-26 09:48:38
运行次数统计 7
获取到的文章标题 高分起名——李的年轻时尚名字
不存在
随机生成的作者是 黄经赋
随机生成的阅读数是 3408
获得的当前发布时间 2020-10-26 10:07:57
运行次数统计 24
获取到的文章标题 小孩起名，男宝宝的名字
不存在
随机生成的作者是 农自怡
随机生成的阅读数是 2824
获得的当前发布时间 2020-10-26 10:08:56
运行次数统计 12
获取到的文章标题 100分起名大全 道德经中的好男孩名字
不存在
随机生成的作者是 林阳秋
随机生成的阅读数是 1310
获得的当前发布时间 2020-10-26 10:10:22
运行次数统计 3
获取到的文章标题 楚辞取名，根据出生日期起个好名字
不存在
随机生成的作者是 能明诚
随机生成的阅读数是 1660
获得的当前发布时间 2020-10-26 10:16:46
运行次数统计 25
获取到的文章标题 新生儿如何起名——女宝宝姓周
不存在
随机生成的作者是 魏飞羽
随机生成的阅读数是 3166
获得的当前发布时间 2020-10-26 10:36:28
运行次数统计 8
获取到的文章标题 高分起名——女孩的好名字
不存在
随机生成的作者是 广敏才
随机生成的阅读数是 1074
获得的当前发布时间 2020-10-26 10:45:24
运行次数统计 13
获取到的文章标题 在线取名——刘的霸气名字
不存在
随机生成的作者是 冯昊昊
随机生成的阅读数是 2554
获得的当前发布时间 2020-10-26 10:46:38
运行次数统计 6
获取到的文章标题 新生儿起名 小张的名字在
不存在
随机生成的作者是 李俊风
随机生成的阅读数是 3728
获得的当前发布时间 2020-10-26 11:15:02
运行次数统计 26
获取到的文章标题 高分起名，猪年三字周姓氏女宝宝名字
不存在
随机生成的作者是 郗良工
随机生成的阅读数是 1523
获得的当前发布时间 2020-10-26 11:15:42
运行次数统计 14
获取到的文章标题 姓名打分——吉祥的老鼠男孩有个好名字
不存在
随机生成的作者是 蓟德惠
随机生成的阅读数是 1196
获得的当前发布时间 2020-10-26 11:21:27
运行次数统计 9
获取到的文章标题 楚辞取名之稀有，独特且漂亮的女孩名字
不存在
随机生成的作者是 古正阳
随机生成的阅读数是 2140
获得的当前发布时间 2020-10-26 11:22:48
运行次数统计 4
获取到的文章标题 科学的宝宝起名的小猪的好名字
不存在
随机生成的作者是 金璞玉
随机生成的阅读数是 3209
获得的当前发布时间 2020-10-26 11:23:37
运行次数统计 7
获取到的文章标题 名字大全之可以使用什么技能为双姓儿童命名
不存在
随机生成的作者是 顾博厚
随机生成的阅读数是 1988
获得的当前发布时间 2020-10-26 11:27:01
运行次数统计 27
获取到的文章标题 科学取名 两字周姓氏
不存在
随机生成的作者是 侯弘方
随机生成的阅读数是 3813
获得的当前发布时间 2020-10-26 11:38:32
运行次数统计 10
获取到的文章标题 怎样取好名 缺少木材的女孩的雅致名字
不存在
随机生成的作者是 广敏才
随机生成的阅读数是 3354
获得的当前发布时间 2020-10-26 11:54:08
运行次数统计 28
获取到的文章标题 国学起名的在猪年命名男孩的提示
不存在
随机生成的作者是 何锐精
随机生成的阅读数是 2468
获得的当前发布时间 2020-10-26 11:54:28
运行次数统计 15
获取到的文章标题 大数据取名的杨大胆大方的名字
不存在
随机生成的作者是 惠永春
随机生成的阅读数是 3344
获得的当前发布时间 2020-10-26 11:56:13
运行次数统计 7
获取到的文章标题 小孩取名的完整的宝宝姓氏，姓陈
不存在
随机生成的作者是 索承泽
随机生成的阅读数是 3952
获得的当前发布时间 2020-10-26 12:18:59
运行次数统计 29
获取到的文章标题 大数据起名 三字周姓男宝宝
不存在
随机生成的作者是 沈乐贤
随机生成的阅读数是 3976
获得的当前发布时间 2020-10-26 12:26:19
运行次数统计 11
获取到的文章标题 大数据取名之漂亮的独特女孩的名字
不存在
随机生成的作者是 莘庆生
随机生成的阅读数是 3646
获得的当前发布时间 2020-10-26 12:31:57
运行次数统计 16
获取到的文章标题 起名需要注意什么 一个叫张的男孩的好名字
不存在
随机生成的作者是 林曾琪
随机生成的阅读数是 2424
获得的当前发布时间 2020-10-26 12:35:53
运行次数统计 30
获取到的文章标题 楚辞取名——，周姓是猪男宝宝的名字
不存在
随机生成的作者是 辛兴运
随机生成的阅读数是 3254
获得的当前发布时间 2020-10-26 12:49:13
运行次数统计 8
获取到的文章标题 热门起名技巧 如果孩子的姓氏​​很特殊，请根据姓氏的特征选择名字
不存在
随机生成的作者是 晃高卓
随机生成的阅读数是 3752
获得的当前发布时间 2020-10-26 13:05:02
运行次数统计 17
获取到的文章标题 最完美的取名 仪表旁有好名声的男孩
不存在
随机生成的作者是 贡元武
随机生成的阅读数是 3212
获得的当前发布时间 2020-10-26 13:13:28
运行次数统计 12
获取到的文章标题 新生儿如何起名的Su的名字很独特
不存在
随机生成的作者是 梁彬郁
随机生成的阅读数是 2611
获得的当前发布时间nohup: ignoring input
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
程序运行的次数 7
休眠时间 80
休眠时间 848
休眠时间 43
休眠时间 846
休眠时间 467
休眠时间 722
休眠时间 427
休眠时间 893
休眠时间 136
这个是栏目id为3 的文章长度 9
运行次数统计 1
获取到的文章标题 起名技巧 康熙字典命名技巧
存在
运行次数统计 2
获取到的文章标题 古诗词取名之根据康熙字典命名的原则和方法
不存在
随机生成的作者是 暨乐和
随机生成的阅读数是 1766
获得的当前发布时间 2020-10-27 09:21:52
这个是栏目id为1 的文章长度 45
运行次数统计 1
获取到的文章标题 小孩起名，如何给张姓宝宝起好名字
存在
运行次数统计 2
获取到的文章标题 新生儿起名 小张的名字在
存在
运行次数统计 3
获取到的文章标题 小孩取名的完整的宝宝姓氏，姓陈
存在
运行次数统计 4
获取到的文章标题 流年取名，小宝贝陈的全名
存在
运行次数统计 5
获取到的文章标题 起名需要注意什么之陈宝宝名字的完整清单
不存在
随机生成的作者是 桓宏义
随机生成的阅读数是 3659
获得的当前发布时间 2020-10-27 09:22:30
这个是栏目id为3 的文章长度 33
运行次数统计 1
获取到的文章标题 新生儿起名 2020RatBoy时尚西方昵称
存在
运行次数统计 2
获取到的文章标题 怎样取好名之漂亮而有意义的宝宝名字
存在
运行次数统计 3
获取到的文章标题 好听的宝宝名字之简单文艺女郎的昵称
存在
运行次数统计 4
获取到的文章标题 流年取名的稻米小子的老鼠男孩
存在
运行次数统计 5
获取到的文章标题 科学起名之昵称
存在
运行次数统计 6
获取到的文章标题 国学起名的农历的第七个月
不存在
随机生成的作者是 幸宜然
随机生成的阅读数是 3129
获得的当前发布时间 2020-10-27 09:23:26
这个是栏目id为3 的文章长度 41
运行次数统计 1
获取到的文章标题 流年起名，如何快速掌握新手的命名技巧，只需记住要点
存在
运行次数统计 2
获取到的文章标题 楚辞取名——如何确保您孩子的名字是杰出的和令人印象深刻的
存在
运行次数统计 3
获取到的文章标题 高分起名之为有普通姓氏的孩子选择什么单词
存在
运行次数统计 4
获取到的文章标题 名字大全之可以使用什么技能为双姓儿童命名
存在
运行次数统计 5
获取到的文章标题 热门起名技巧 如果孩子的姓氏​​很特殊，请根据姓氏的特征选择名字
存在
运行次数统计 6
获取到的文章标题 起名技巧 可以根据生肖命名的孩子
不存在
随机生成的作者是 满皓轩
随机生成的阅读数是 2559
获得的当前发布时间 2020-10-27 09:28:17
这个是栏目id为3 的文章长度 90
运行次数统计 1
获取到的文章标题 楚辞取名之稀有，独特且漂亮的女孩名字
存在
运行次数统计 2
获取到的文章标题 怎样取好名 缺少木材的女孩的雅致名字
存在
运行次数统计 3
获取到的文章标题 大数据取名之漂亮的独特女孩的名字
存在
运行次数统计 4
获取到的文章标题 新生儿如何起名的Su的名字很独特
存在
运行次数统计 5
获取到的文章标题 新生儿起名，在它旁边的木名字的老鼠女孩
存在
运行次数统计 6
获取到的文章标题 免费的宝宝起名之大气的女孩名字与诗歌
不存在
随机生成的作者是 秦明远
随机生成的阅读数是 2506
获得的当前发布时间 2020-10-27 09:28:57
这个是栏目id为3 的文章长度 19
运行次数统计 1
获取到的文章标题 楚辞取名，根据出生日期起个好名字
存在
运行次数统计 2
获取到的文章标题 科学起名，看另一半的形象
不存在
随机生成的作者是 邴阳云
随机生成的阅读数是 1351
获得的当前发布时间 2020-10-27 09:33:11
这个是栏目id为3 的文章长度 81
运行次数统计 1
获取到的文章标题 免费的宝宝起名之杨的简单好听的名字
存在
运行次数统计 2
获取到的文章标题 起名网的最适合老鼠男孩的好名字
存在
运行次数统计 3
获取到的文章标题 100分起名大全 道德经中的好男孩名字
存在
运行次数统计 4
获取到的文章标题 在线取名——刘的霸气名字
存在
运行次数统计 5
获取到的文章标题 姓名打分——吉祥的老鼠男孩有个好名字
存在
运行次数统计 6
获取到的文章标题 大数据取名的杨大胆大方的名字
存在
运行次数统计 7
获取到的文章标题 起名需要注意什么 一个叫张的男孩的好名字
存在
运行次数统计 8
获取到的文章标题 最完美的取名 仪表旁有好名声的男孩
存在
运行次数统计 9
获取到的文章标题 生辰八字取名之西方男孩与你同名
存在
运行次数统计 10
获取到的文章标题 最完美的起名，李姓男孩以岳的名字命名
存在
运行次数统计 11
获取到的文章标题 姓名打分之张的男孩名字
不存在
随机生成的作者是 家敏学
随机生成的阅读数是 2065
获得的当前发布时间 2020-10-27 09:35:16
这个是栏目id为2 的文章长度 149
运行次数统计 1
获取到的文章标题 大数据起名 男宝宝的名字
存在
运行次数统计 2
获取到的文章标题 八字取名之漂亮的单字符钟姓男孩
存在
运行次数统计 3
获取到的文章标题 新生儿取名的气氛很好
存在
运行次数统计 4
获取到的文章标题 自动起名之梦想出差意味着什么
存在
运行次数统计 5
获取到的文章标题 科学取名，姓霍的女孩的好名字
存在
运行次数统计 6
获取到的文章标题 流行的宝宝取名的猪年刘姓
存在
运行次数统计 7
获取到的文章标题 流行的宝宝取名，猪年男孩叫吴的名字
存在
运行次数统计 8
获取到的文章标题 起名网 特色宝宝名字
存在
运行次数统计 9
获取到的文章标题 大数据取名的很好听王的男孩名字
存在
运行次数统计 10
获取到的文章标题 起名需要注意什么 男宝宝名字郑
存在
运行次数统计 11
获取到的文章标题 好听的宝宝名字之郑姓女宝宝
存在
运行次数统计 12
获取到的文章标题 免费的宝宝取名，宝宝姓李
存在
运行次数统计 13
获取到的文章标题 小孩起名，男宝宝的名字
存在
运行次数统计 14
获取到的文章标题 新生儿如何起名——女宝宝姓周
存在
运行次数统计 15
获取到的文章标题 高分起名，猪年三字周姓氏女宝宝名字
存在
运行次数统计 16
获取到的文章标题 科学取名 两字周姓氏
存在
运行次数统计 17
获取到的文章标题 国学起名的在猪年命名男孩的提示
存在
运行次数统计 18
获取到的文章标题 大数据起名 三字周姓男宝宝
存在
运行次数统计 19
获取到的文章标题 楚辞取名——，周姓是猪男宝宝的名字
存在
运行次数统计 20
获取到的文章标题 新生儿如何起名 梦见一个人独自哭泣意味着什么？
存在
运行次数统计 21
获取到的文章标题 在线起名，梦见一条狗在吃蛇，这意味着什么？
存在
运行次数统计 22
获取到的文章标题 科学取名——欧阳三字女宝宝名字
不存在
随机生成的作者是 茹德元
随机生成的阅读数是 1358
获得的当前发布时间 2020-10-27 09:35:26
这个是栏目id为3 的文章长度 19
运行次数统计 1
获取到的文章标题 小孩取名——喜宝宝的好名字
存在
运行次数统计 2
获取到的文章标题 科学的宝宝起名的小猪的好名字
存在
运行次数统计 3
获取到的文章标题 科学的宝宝起名的小猪名字和汉字
不存在
随机生成的作者是 钟君浩
随机生成的阅读数是 3997
获得的当前发布时间 2020-10-27 09:36:03
运行次数统计Exception in thread lanmu_id_4:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "fabu0923.py", line 186, in lanmu_id_4
    xieru_zong = Article_zan.query.filter(Article_zan.lanmu_id == 4).all()[changdu]
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3341, in all
    return list(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3525, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3540, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3518, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
    execution_options=execution_options,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
    engine, execution_options
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2305, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2343, in _wrap_pool_connect
    e, dialect, self
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1585, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Exception in thread lanmu_id_5:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "fabu0923.py", line 235, in lanmu_id_5
    xieru_zong = Article_zan.query.filter(Article_zan.lanmu_id == 5).all()[changdu]
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3341, in all
    return list(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3525, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3540, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3518, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
    execution_options=execution_options,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
    engine, execution_options
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2305, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2343, in _wrap_pool_connect
    e, dialect, self
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1585, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Exception in thread lanmu_id_6:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "fabu0923.py", line 284, in lanmu_id_6
    xieru_zong = Article_zan.query.filter(Article_zan.lanmu_id == 6).all()[changdu]
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3341, in all
    return list(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3525, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3540, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3518, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1141, in connection
    execution_options=execution_options,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
    engine, execution_options
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2305, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2343, in _wrap_pool_connect
    e, dialect, self
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1585, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
(Background on this error at: http://sqlalche.me/e/13/e3q8)
nohup: ignoring input
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
程序运行的次数 7
休眠时间 934
休眠时间 897
休眠时间 461
休眠时间 493
休眠时间 240
休眠时间 307
休眠时间 114
休眠时间 485
休眠时间 124
这个是栏目id为3 的文章长度 46
运行次数统计 1
获取到的文章标题 起名技巧 可以根据生肖命名的孩子
存在
运行次数统计 2
获取到的文章标题 古诗词取名——命名孩子时应注意哪些问题，以及如何正确使用五个单词
存在
运行次数统计 3
获取到的文章标题 免费的宝宝起名之哪些宝宝名字最适合使用“水”这五个词，应注意哪些问题
存在
运行次数统计 4
获取到的文章标题 流行的宝宝取名 如何命名猪年出生的孩子
存在
运行次数统计 5
获取到的文章标题 流年取名，常见的姓氏命名问题是什么，以及如何克服它们
存在
运行次数统计 6
获取到的文章标题 科学的宝宝起名，如何用诗歌赋予女孩诗意的名字
不存在
随机生成的作者是 沃彬彬
随机生成的阅读数是 3471
获得的当前发布时间 2020-10-28 09:23:04
这个是栏目id为3 的文章长度 35
运行次数统计 1
获取到的文章标题 好听的宝宝名字之简单文艺女郎的昵称
存在
运行次数统计 2
获取到的文章标题 流年取名的稻米小子的老鼠男孩
存在
运行次数统计 3
获取到的文章标题 科学起名之昵称
存在
运行次数统计 4
获取到的文章标题 国学起名的农历的第七个月
存在
运行次数统计 5
获取到的文章标题 周易起名——西式奶牛的昵称
存在
运行次数统计 6
获取到的文章标题 最完美的起名 如何获得母牛的昵称
不存在
随机生成的作者是 那欣荣
随机生成的阅读数是 1535
获得的当前发布时间 2020-10-28 09:23:13
这个是栏目id为3 的文章长度 91
运行次数统计 1
获取到的文章标题 怎样取好名 缺少木材的女孩的雅致名字
存在
运行次数统计 2
获取到的文章标题 大数据取名之漂亮的独特女孩的名字
存在
运行次数统计 3
获取到的文章标题 新生儿如何起名的Su的名字很独特
存在
运行次数统计 4
获取到的文章标题 新生儿起名，在它旁边的木名字的老鼠女孩
存在
运行次数统计 5
获取到的文章标题 免费的宝宝起名之大气的女孩名字与诗歌
存在
运行次数统计 6
获取到的文章标题 周易起名，夏姓女孩的好名字
存在
运行次数统计 7
获取到的文章标题 最完美的起名——优雅的女孩名字与诗歌
存在
运行次数统计 8
获取到的文章标题 周易取名，童话冷女孩的名字
存在
运行次数统计 9
获取到的文章标题 在线起名的宝贝女孩名字用一个词
存在
运行次数统计 10
获取到的文章标题 新生儿如何起名，古代诗歌中宝宝名字的完整列表
存在
运行次数统计 11
获取到的文章标题 新生儿如何起名之宝宝鼠标的简单好命名技巧
存在
运行次数统计 12
获取到的文章标题 起名技巧之简单而漂亮的宝宝鼠标名称可以共享
存在
运行次数统计 13
获取到的文章标题 科学的宝宝起名，如何获得一个慷慨的外来老鼠宝宝的名字
存在
运行次数统计 14
获取到的文章标题 免费的宝宝起名 简单优雅的鼠宝宝女孩的名字
存在
运行次数统计 15
获取到的文章标题 周易起名，NalanCi的宝宝命名技巧
存在
运行次数统计 16
获取到的文章标题 最完美的起名之纳兰慈的女宝宝名字的完整列表
不存在
随机生成的作者是 盖康宁
随机生成的阅读数是 2558
获得的当前发布时间 2020-10-28 09:25:11
这个是栏目id为3 的文章长度 20
运行次数统计 1
获取到的文章标题 科学起名，看另一半的形象
存在
运行次数统计 2
获取到的文章标题 值得推荐的起名，十二生肖的猪名字
不存在
随机生成的作者是 宿星剑
随机生成的阅读数是 3391
获得的当前发布时间 2020-10-28 09:26:16
这个是栏目id为3 的文章长度 10
运行次数统计 1
获取到的文章标题 古诗词取名之根据康熙字典命名的原则和方法
存在
运行次数统计 2
获取到的文章标题 免费八字取名——康熙字典中常用单词的列表
不存在
随机生成的作者是 屠明辉
随机生成的阅读数是 3571
获得的当前发布时间 2020-10-28 09:28:50
这个是栏目id为3 的文章长度 21
运行次数统计 1
获取到的文章标题 科学的宝宝起名的小猪名字和汉字
存在
运行次数统计 2
获取到的文章标题 取名技巧——猪仔的好名字是什么
存在
运行次数统计 3
获取到的文章标题 古诗词起名，猪姓和宝宝名字的好意思
不存在
随机生成的作者是 侯志学
随机生成的阅读数是 1043
获得的当前发布时间 2020-10-28 09:29:14
这个是栏目id为3 的文章长度 82
运行次数统计 1
获取到的文章标题 起名网的最适合老鼠男孩的好名字
存在
运行次数统计 2
获取到的文章标题 100分起名大全 道德经中的好男孩名字
存在
运行次数统计 3
获取到的文章标题 在线取名——刘的霸气名字
存在
运行次数统计 4
获取到的文章标题 姓名打分——吉祥的老鼠男孩有个好名字
存在
运行次数统计 5
获取到的文章标题 大数据取名的杨大胆大方的名字
存在
运行次数统计 6
获取到的文章标题 起名需要注意什么 一个叫张的男孩的好名字
存在
运行次数统计 7
获取到的文章标题 最完美的取名 仪表旁有好名声的男孩
存在
运行次数统计 8
获取到的文章标题 生辰八字取名之西方男孩与你同名
存在
运行次数统计 9
获取到的文章标题 最完美的起名，李姓男孩以岳的名字命名
存在
运行次数统计 10
获取到的文章标题 姓名打分之张的男孩名字
存在
运行次数统计 11
获取到的文章标题 周易起名的古老而傲慢而美丽的男孩名字
不存在
随机生成的作者是 李俊风
随机生成的阅读数是 2655
获得的当前发布时间 2020-10-28 09:29:23
这个是栏目id为2 的文章长度 169
运行次数统计 1
获取到的文章标题 在线起名，梦见一条狗在吃蛇，这意味着什么？
存在
运行次数统计 2
获取到的文章标题 科学取名——欧阳三字女宝宝名字
存在
运行次数统计 3
获取到的文章标题 流年起名——以欧阳姓氏命名的女宝宝
存在
运行次数统计 4
获取到的文章标题 小孩取名——上官三字姓
存在
运行次数统计 5
获取到的文章标题 宝宝怎么取名，上官姓女宝宝名单
存在
运行次数统计 6
获取到的文章标题 大数据取名的三字符女宝宝的名字
存在
运行次数统计 7
获取到的文章标题 高分取名 女宝宝名字列表
存在
运行次数统计 8
获取到的文章标题 免费八字取名之女宝宝姓Sima的三个字符的名字
存在
运行次数统计 9
获取到的文章标题 古诗词起名——女宝宝姓Sima的两个字符的名字
存在
运行次数统计 10
获取到的文章标题 古诗词起名 女宝宝名字行
存在
运行次数统计 11
获取到的文章标题 小孩取名，男宝宝名字坑
存在
运行次数统计 12
获取到的文章标题 取名技巧的宝宝姓洪
存在
运行次数统计 13
获取到的文章标题 科学取名之女宝宝名字洪
存在
运行次数统计 14
获取到的文章标题 免费八字取名之宝姓男孩的名字
存在
运行次数统计 15
获取到的文章标题 新生儿如何起名，女宝宝宝
存在
运行次数统计 16
获取到的文章标题 小孩取名——最新又好听的名字Pan，男孩的名字
存在
运行次数统计 17
获取到的文章标题 大数据起名，好姑娘名字仁
存在
运行次数统计 18
获取到的文章标题 起名需要注意什么的简单易听的女孩名字
存在
运行次数统计 19
获取到的文章标题 姓名打分 好孩子的名字傅
存在
运行次数统计 20
获取到的文章标题 最完美的取名 傅的好孩子名字推荐
存在
运行次数统计 21
获取到的文章标题 姓名打分的漂亮的两个字符的男孩名字傅
存在
运行次数统计 22
获取到的文章标题 起名大全的龙姓宝宝如何取名呢？
不存在
随机生成的作者是 蒙宏邈
随机生成的阅读数是 2677
获得的当前发布时间 2020-10-28 09:36:13
这个是栏目id为1 的文章长度 50
运行次数统计 1
获取到的文章标题 高分取名——2020年宝宝名字列表
存在
运行次数统计 2
获取到的文章标题 如何利用八字起名的最时尚和最西方的宝宝名字列表
存在
运行次数统计 3
获取到的文章标题 最完美的起名 什么样的宝宝名字陈听起来不错
存在
运行次数统计 4
获取到的文章标题 大数据起名——优雅大气的宝宝名字陈
存在
运行次数统计 5
获取到的文章标题 周易取名之富宝宝的名字陈
不存在
随机生成的作者是 家嘉言
随机生成的阅读数是 3558
获得的当前发布时间 2020-10-28 09:36:43
运行次数统计 3
获取到的文章标题 高分取名的十二生肖鸡的宝宝名字
不存在
随机生成的作者是 郑凯泽
随机生成的阅读数是 1045
获得的当前发布时间 2020-10-28 10:06:37
运行次数统计 17
获取到的文章标题 取名网——宝贝女孩名字用优雅的字符
不存在
随机生成的作者是 邱茂勋
随机生成的阅读数是 3154
获得的当前发布时间 2020-10-28 10:09:41
运行次数统计 23
获取到的文章标题 值得推荐的起名 不错的三个字符的叶姓
不存在
随机生成的作者是 乌嘉致
随机生成的阅读数是 1762
获得的当前发布时间 2020-10-28 10:10:34
运行次数统计 12
获取到的文章标题 大数据取名之仙奇冷男孩的名字
不存在
随机生成的作者是 程飞驰
随机生成的阅读数是 3278
获得的当前发布时间 2020-10-28 10:10:53
运行次数统计 24
获取到的文章标题 姓名打分的两个字符的叶姓
不存在
随机生成的作者是 束温茂
随机生成的阅读数是 3279
获得的当前发布时间 2020-10-28 10:27:46
运行次数统计 7
获取到的文章标题 姓名打分，如何善用命名方式和选择含义清晰的单词
不存在
随机生成的作者是 越俊达
随机生成的阅读数是 2170
获得的当前发布时间 2020-10-28 10:38:34
运行次数统计 18
获取到的文章标题 取名技巧的女孩如何使用优雅的人物来命名
不存在
随机生成的作者是 谭皓轩
随机生成的阅读数是 3100
获得的当前发布时间 2020-10-28 10:49:46
运行次数统计 13
获取到的文章标题 好听的宝宝名字——Sun的新名字
不存在
随机生成的作者是 钭志义
随机生成的阅读数是 3096
获得的当前发布时间 2020-10-28 10:54:15
运行次数统计 6
获取到的文章标题 国学起名——四字姓陈
不存在
随机生成的作者是 莘英哲
随机生成的阅读数是 2351
获得的当前发布时间 2020-10-28 10:56:09
运行次数统计 25
获取到的文章标题 宝宝怎么取名之外国宝宝的名字朱
不存在
随机生成的作者是 蓟德惠
随机生成的阅读数是 1011
获得的当前发布时间 2020-10-28 11:01:27
运行次数统计 19
获取到的文章标题 科学的宝宝起名之温柔，安静且富有诗意的女孩名字
不存在
随机生成的作者是 充浩穰
随机生成的阅读数是 3049
获得的当前发布时间 2020-10-28 11:25:01
运行次数统计 26
获取到的文章标题 楚辞起名，很高兴听男宝宝名字柯
不存在
随机生成的作者是 冯建白
随机生成的阅读数是 3780
获得的当前发布时间 2020-10-28 11:26:17
运行次数统计 14
获取到的文章标题 起名需要注意什么 好孩子的名字在“LantingPre序言”中
不存在
随机生成的作者是 沈嘉实
随机生成的阅读数是 2478
获得的当前发布时间 2020-10-28 11:27:04
运行次数统计 8
获取到的文章标题 取名技巧，命名孩子时如何减少重复名称的出现
不存在
随机生成的作者是 燕志学
随机生成的阅读数是 3493
获得的当前发布时间 2020-10-28 11:48:41
运行次数统计 27
获取到的文章标题 怎样取好名之适合宝宝的名字柯
不存在
随机生成的作者是 徐光启
随机生成的阅读数是 3013
获得的当前发布时间 2020-10-28 11:50:37
运行次数统计 15
获取到的文章标题 国学起名之罕见而独特的男孩名字
不存在
随机生成的作者是 梁嘉珍
随机生成的阅读数是 1737
获得的当前发布时间 2020-10-28 11:58:06
运行次数统计 7
获取到的文章标题 大数据起名，宝宝陈的诗意名字
不存在
随机生成的作者是 广文成
随机生成的阅读数是 2922
获得的当前发布时间 2020-10-28 12:03:59
运行次数统计 20
获取到的文章标题 取名技巧的童话女孩的名字
不存在
随机生成的作者是 董宇文
随机生成的阅读数是 1513
获得的当前发布时间 2020-10-28 12:07:23
运行次数统计 28
获取到的文章标题 古诗词取名的姓柯的男宝宝姓的完整列表
不存在
随机生成的作者是 鄂宏朗
随机生成的阅读数是 2845
获得的当前发布时间 2020-10-28 12:08:12
运行次数统计 29
获取到的文章标题 姓名打分 纪念宝宝姓氏的两个单词
不存在
随机生成的作者是 濮承德
随机生成的阅读数是 2671
获得的当前发布时间 2020-10-28 12:31:45
运行次数统计 16
获取到的文章标题 100分起名大全之有诗意的好男孩名字
不存在
随机生成的作者是 唐安国
随机生成的阅读数是 2038
获得的当前发布时间 2020-10-28 12:31:57
运行次数统计 21
获取到的文章标题 科学取名的老鼠女郎有个漂亮的名字
不存在
随机生成的作者是 步宏爽
随机生成的阅读数是 3724
获得的当前发布时间 2020-10-28 12:39:18
运行次数统计 30
获取到的文章标题 起名网之三字吉姓女宝宝名
不存在
随机生成的作者是 那欣荣
随机生成的阅读数是 1776
获得的当前发布时间 2020-10-28 12:51:56
运行次数统计 9
获取到的文章标题 最完美的起名的选择好看的单词作为名称。好看的名字有一些特点
不存在
随机生成的作者是 梁嘉珍
随机生成的阅读数是 3590
获得的当前发布时间 2020-10-28 13:08:39
运行次数统计 31
获取到的文章标题 古诗词取名——推荐的男宝宝名字
不存在
随机生成的作者是 菱新觉
随机生成的阅读数是 1081
获得的当前发布时间 2020-10-28 13:09:11
运行次数统计 17
获取到的文章标题 楚辞取名，古代诗歌中火词旁的男孩的名字
不存在
随机生成的作者是 边德寿
随机生成的阅读数是 3658
获得的当前发布时间 2020-10-28 13:10:11
运行次数统计 22
获取到的文章标题 楚辞取名的2020年最气质的女孩名字
不存在
随机生成的作者是 邴阳云
随机生成的阅读数是 3062
获得的当前发布时间 2020-10-28 13:11:28
运行次数统计 4
获取到的文章标题 免费的宝宝起名——如何给孩子起个漂亮的名字
不存在
随机生成的作者是 蒯永元
随机生成的阅读数是 2742
获得的当前发布时间 2020-10-28 13:40:46
运行次数统计 8
获取到的文章标题 免费的宝宝起名 徐的好名字应该出现什么词
不存在
随机生成的作者是 家嘉言
随机生成的阅读数是 2436
获得的当前发布时间 2020-10-28 13:41:01
运行次数统计 23
获取到的文章标题 小孩起名之2020年一个叫刘的老鼠女孩的好名字
不存在
随机生成的作者是 晃高卓
随机生成的阅读数是 1285
获得的当前发布时间 2020-10-28 13:43:46
运行次数统计 18
获取到的文章标题 周易起名——一个姓陈的男孩的好名字
不存在
随机生成的作者是 金康宁
随机生成的阅读数是 1315
获得的当前发布时间 2020-10-28 13:48:02
运行次数统计Execution of job "duoxiancheng (trigger: cron[hour='9', minute='21', second='9'], next run at: 2020-10-29 09:21:09 CST)" skipped: maximum number of running instances reached (1)
Execution of job "duoxiancheng (trigger: cron[hour='9', minute='21', second='9'], next run at: 2020-10-30 09:21:09 CST)" skipped: maximum number of running instances reached (1)
nohup: ignoring input
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
程序运行的次数 7
休眠时间 185
休眠时间 288
休眠时间 295
休眠时间 754
休眠时间 110
休眠时间 484
休眠时间 113
休眠时间 64
休眠时间 281
这个是栏目id为3 的文章长度 23
运行次数统计 1
获取到的文章标题 古诗词起名，猪姓和宝宝名字的好意思
存在
运行次数统计 2
获取到的文章标题 免费的宝宝起名——如何给孩子起个漂亮的名字
存在
运行次数统计 3
获取到的文章标题 起名大全——漂亮的宝宝名字的完整列表
不存在
随机生成的作者是 耿彭越
随机生成的阅读数是 3506
获得的当前发布时间 2020-10-31 09:22:13
这个是栏目id为3 的文章长度 101
运行次数统计 1
获取到的文章标题 新生儿如何起名之宝宝鼠标的简单好命名技巧
存在
运行次数统计 2
获取到的文章标题 起名技巧之简单而漂亮的宝宝鼠标名称可以共享
存在
运行次数统计 3
获取到的文章标题 科学的宝宝起名，如何获得一个慷慨的外来老鼠宝宝的名字
存在
运行次数统计 4
获取到的文章标题 免费的宝宝起名 简单优雅的鼠宝宝女孩的名字
存在
运行次数统计 5
获取到的文章标题 周易起名，NalanCi的宝宝命名技巧
存在
运行次数统计 6
获取到的文章标题 最完美的起名之纳兰慈的女宝宝名字的完整列表
存在
运行次数统计 7
获取到的文章标题 取名网——宝贝女孩名字用优雅的字符
存在
运行次数统计 8
获取到的文章标题 取名技巧的女孩如何使用优雅的人物来命名
存在
运行次数统计 9
获取到的文章标题 科学的宝宝起名之温柔，安静且富有诗意的女孩名字
存在
运行次数统计 10
获取到的文章标题 取名技巧的童话女孩的名字
存在
运行次数统计 11
获取到的文章标题 科学取名的老鼠女郎有个漂亮的名字
存在
运行次数统计 12
获取到的文章标题 楚辞取名的2020年最气质的女孩名字
存在
运行次数统计 13
获取到的文章标题 小孩起名之2020年一个叫刘的老鼠女孩的好名字
存在
运行次数统计 14
获取到的文章标题 小孩起名的好仙女的名字
存在
运行次数统计 15
获取到的文章标题 好听的宝宝名字之漂亮独特且稀有的女孩名字
存在
运行次数统计 16
获取到的文章标题 周易取名之老鼠女郎的名字简单大方
不存在
随机生成的作者是 郗良工
随机生成的阅读数是 2671
获得的当前发布时间 2020-10-31 09:23:01
这个是栏目id为3 的文章长度 51
运行次数统计 1
获取到的文章标题 科学的宝宝起名，如何用诗歌赋予女孩诗意的名字
存在
运行次数统计 2
获取到的文章标题 姓名打分，如何善用命名方式和选择含义清晰的单词
存在
运行次数统计 3
获取到的文章标题 取名技巧，命名孩子时如何减少重复名称的出现
存在
运行次数统计 4
获取到的文章标题 最完美的起名的选择好看的单词作为名称。好看的名字有一些特点
存在
运行次数统计 5
获取到的文章标题 取名网之为什么名字会影响一个人的性格
存在
运行次数统计 6
获取到的文章标题 生辰八字取名——如何使用成语给孩子起好名字
不存在
随机生成的作者是 宋志泽
随机生成的阅读数是 2815
获得的当前发布时间 2020-10-31 09:23:03
这个是栏目id为1 的文章长度 55
运行次数统计 1
获取到的文章标题 国学起名——四字姓陈
存在
运行次数统计 2
获取到的文章标题 大数据起名，宝宝陈的诗意名字
存在
运行次数统计 3
获取到的文章标题 免费的宝宝起名 徐的好名字应该出现什么词
存在
运行次数统计 4
获取到的文章标题 取名网的如何为成宝取名
存在
运行次数统计 5
获取到的文章标题 八字取名 马姓宝宝的命名技巧
不存在
随机生成的作者是 鱼子民
随机生成的阅读数是 1985
获得的当前发布时间 2020-10-31 09:24:14
这个是栏目id为3 的文章长度 39
运行次数统计 1
获取到的文章标题 周易起名——西式奶牛的昵称
存在
运行次数统计 2
获取到的文章标题 最完美的起名 如何获得母牛的昵称
存在
运行次数统计 3
获取到的文章标题 大数据取名——外来老鼠宝宝的命名技巧
存在
运行次数统计 4
获取到的文章标题 起名需要注意什么，可爱和外来老鼠宝宝的昵称
存在
运行次数统计 5
获取到的文章标题 新生儿起名 适合八月份的宝宝名字
存在
运行次数统计 6
获取到的文章标题 周易起名，如何在八月获得鼠宝宝的名字
不存在
随机生成的作者是 牛健柏
随机生成的阅读数是 1367
获得的当前发布时间 2020-10-31 09:25:50
这个是栏目id为2 的文章长度 189
运行次数统计 1
获取到的文章标题 姓名打分的漂亮的两个字符的男孩名字傅
存在
运行次数统计 2
获取到的文章标题 起名大全的龙姓宝宝如何取名呢？
存在
运行次数统计 3
获取到的文章标题 值得推荐的起名 不错的三个字符的叶姓
存在
运行次数统计 4
获取到的文章标题 姓名打分的两个字符的叶姓
存在
运行次数统计 5
获取到的文章标题 宝宝怎么取名之外国宝宝的名字朱
存在
运行次数统计 6
获取到的文章标题 楚辞起名，很高兴听男宝宝名字柯
存在
运行次数统计 7
获取到的文章标题 怎样取好名之适合宝宝的名字柯
存在
运行次数统计 8
获取到的文章标题 古诗词取名的姓柯的男宝宝姓的完整列表
存在
运行次数统计 9
获取到的文章标题 姓名打分 纪念宝宝姓氏的两个单词
存在
运行次数统计 10
获取到的文章标题 起名网之三字吉姓女宝宝名
存在
运行次数统计 11
获取到的文章标题 古诗词取名——推荐的男宝宝名字
存在
运行次数统计 12
获取到的文章标题 起名大全的姓邓的女孩的好名字
存在
运行次数统计 13
获取到的文章标题 新生儿起名的宝宝名字与靖
存在
运行次数统计 14
获取到的文章标题 自动起名之的新宝宝名字
存在
运行次数统计 15
获取到的文章标题 起名大全 的稀有和古董宝宝名字
存在
运行次数统计 16
获取到的文章标题 在线取名的最好的宝宝名字
存在
运行次数统计 17
获取到的文章标题 科学的宝宝起名的吉祥的宝宝名字
存在
运行次数统计 18
获取到的文章标题 生辰八字取名——非常好的宝宝名字的完整列表
这个是栏目id为3 的文章长度 11
运行次数统计 1
获取到的文章标题 免费八字取名——康熙字典中常用单词的列表
存在
运行次数统计 19
存在
运行次数统计 2
获取到的文章标题 自动起名——如何命名康熙字典
不存在
随机生成的作者是 程飞驰
随机生成的阅读数是 2450
获得的当前发布时间 2020-10-31 09:26:04
获取到的文章标题 最完美的取名的带漾的猪宝宝名字大全推荐
存在
运行次数统计 20
获取到的文章标题 起名网之温柔而有意义的小猪名字的完整列表
存在
运行次数统计 21
获取到的文章标题 大数据取名 猪宝宝的名字
存在
运行次数统计 22
获取到的文章标题 值得推荐的起名 猪的女宝宝名字
不存在
随机生成的作者是 龙阳煦
随机生成的阅读数是 3125
获得的当前发布时间 2020-10-31 09:26:05
这个是栏目id为3 的文章长度 22
运行次数统计 1
获取到的文章标题 高分取名的十二生肖鸡的宝宝名字
存在
运行次数统计 2
获取到的文章标题 取名技巧的十二生肖兔的宝宝名字
不存在
随机生成的作者是 索承泽
随机生成的阅读数是 2278
获得的当前发布时间 2020-10-31 09:29:13
这个是栏目id为3 的文章长度 92
运行次数统计 1
获取到的文章标题 周易起名的古老而傲慢而美丽的男孩名字
存在
运行次数统计 2
获取到的文章标题 大数据取名之仙奇冷男孩的名字
存在
运行次数统计 3
获取到的文章标题 好听的宝宝名字——Sun的新名字
存在
运行次数统计 4
获取到的文章标题 起名需要注意什么 好孩子的名字在“LantingPre序言”中
存在
运行次数统计 5
获取到的文章标题 国学起名之罕见而独特的男孩名字
存在
运行次数统计 6
获取到的文章标题 100分起名大全之有诗意的好男孩名字
存在
运行次数统计 7
获取到的文章标题 楚辞取名，古代诗歌中火词旁的男孩的名字
存在
运行次数统计 8
获取到的文章标题 周易起名——一个姓陈的男孩的好名字
存在
运行次数统计 9
获取到的文章标题 大数据起名的有田姓的男孩有个好名字
存在
运行次数统计 10
获取到的文章标题 八字取名——古代霸气男孩的名字
存在
运行次数统计 11
获取到的文章标题 生辰八字起名，阳光明媚的男孩名字与易
不存在
随机生成的作者是 幸宜然
随机生成的阅读数是 3920
获得的当前发布时间 2020-10-31 09:33:44
运行次数统计 17
获取到的文章标题 小孩起名——诗意的女孩名字
不存在
随机生成的作者是 赖宜春
随机生成的阅读数是 1267
获得的当前发布时间 2020-10-31 10:05:03
运行次数统计 23
获取到的文章标题 楚辞起名 司马女宝宝的名字
不存在
随机生成的作者是 夏高洁
随机生成的阅读数是 2465
获得的当前发布时间 2020-10-31 10:08:33
运行次数统计 3
获取到的文章标题 楚辞取名之十二生肖狗的宝宝名字
不存在
随机生成的作者是 韶修然
随机生成的阅读数是 1123
获得的当前发布时间 2020-10-31 10:12:38
运行次数统计 12
获取到的文章标题 怎样取好名 那个老鼠男孩有一个英俊且举止得体的名字
不存在
随机生成的作者是 姚鸿羲
随机生成的阅读数是 2198
获得的当前发布时间 2020-10-31 10:17:04
运行次数统计 24
获取到的文章标题 大数据起名，男宝宝名字
不存在
随机生成的作者是 谷雅健
随机生成的阅读数是 1102
获得的当前发布时间 2020-10-31 10:34:53
运行次数统计 18
获取到的文章标题 姓名打分——女孩的文学森林系的好名字
不存在
随机生成的作者是 茹德元
随机生成的阅读数是 3670
获得的当前发布时间 2020-10-31 10:45:13
运行次数统计 13
获取到的文章标题 国学起名，Li骚美丽的男孩名字
不存在
随机生成的作者是 鱼子民
随机生成的阅读数是 2108
获得的当前发布时间 2020-10-31 10:55:44
运行次数统计 25
获取到的文章标题 值得推荐的起名 丁宝宝的名字
不存在
随机生成的作者是 暨乐和
随机生成的阅读数是 1371
获得的当前发布时间 2020-10-31 11:00:58
运行次数统计 7
获取到的文章标题 古诗词起名的如何给宝宝起一个昵称，宝宝的昵称技巧
不存在
随机生成的作者是 訾温纶
随机生成的阅读数是 2409
获得的当前发布时间 2020-10-31 11:14:27
运行次数统计 6
获取到的文章标题 流年起名之命名宝宝的常用方法列表
不存在
随机生成的作者是 幸宜然
随机生成的阅读数是 1607
获得的当前发布时间 2020-10-31 11:20:10
运行次数统计 19
获取到的文章标题 怎样起好名——沙棘姓氏女孩的雅致名字
不存在
随机生成的作者是 权伟祺
随机生成的阅读数是 2698
获得的当前发布时间 2020-10-31 11:25:34
运行次数统计 14
获取到的文章标题 生辰八字起名——老鼠男孩有个吉祥的名字
不存在
随机生成的作者是 通坚秉
随机生成的阅读数是 3488
获得的当前发布时间 2020-10-31 11:26:32
运行次数统计 26
获取到的文章标题 宝宝怎么取名之女宝宝姓彭
不存在
随机生成的作者是 璩烨烨
随机生成的阅读数是 1155
获得的当前发布时间 2020-10-31 11:36:15
运行次数统计 27
获取到的文章标题 高分起名的三字好孩子的名字胡
不存在
随机生成的作者是 李成济
随机生成的阅读数是 3022
获得的当前发布时间 2020-10-31 11:58:22
运行次数统计 20
获取到的文章标题 宝宝怎么取名 姓刘的女孩名字很好
不存在
随机生成的作者是 梁彬郁
随机生成的阅读数是 3863
获得的当前发布时间 2020-10-31 12:02:05
运行次数统计 15
获取到的文章标题 姓名打分 这个男孩的霸气名字叫陈
不存在
随机生成的作者是 公嘉珍
随机生成的阅读数是 2063
获得的当前发布时间 2020-10-31 12:06:05
运行次数统计 28
获取到的文章标题 古诗词取名，胡姓好孩子的名字
不存在
随机生成的作者是 仰同济
随机生成的阅读数是 3979
获得的当前发布时间 2020-10-31 12:21:44
运行次数统计 21
获取到的文章标题 楚辞起名——杨姓女孩有一个好听的外国名字
不存在
随机生成的作者是 钟成双
随机生成的阅读数是 3078
获得的当前发布时间 2020-10-31 12:32:51
运行次数统计 7
获取到的文章标题 古诗词起名之命名宝宝金的关键要素
不存在
随机生成的作者是 侯修谨
随机生成的阅读数是 2571
获得的当前发布时间 2020-10-31 12:44:05
运行次数统计 16
获取到的文章标题 100分起名大全——洋气，寓意男孩的名字陈
不存在
随机生成的作者是 庾高澹
随机生成的阅读数是 3828
获得的当前发布时间 2020-10-31 12:44:55
运行次数统计 29
获取到的文章标题 好听的宝宝名字，男宝宝名字彭
不存在
随机生成的作者是 漕弘阔
随机生成的阅读数是 1182
获得的当前发布时间 2020-10-31 12:50:36
运行次数统计 8
获取到的文章标题 楚辞起名 如何为女孩选择漂亮的单词
不存在
随机生成的作者是 通正文
随机生成的阅读数是 2397
获得的当前发布时间 2020-10-31 13:13:44
运行次数统计 22
获取到的文章标题 古诗词取名之2020年老鼠女孩的独特名字
不存在
随机生成的作者是 郑凯泽
随机生成的阅读数是 1013
获得的当前发布时间 2020-10-31 13:14:56
运行次数统计 17
获取到的文章标题 起名需要注意什么的适合男孩用有意义的单词命名
不存在
随机生成的作者是 潘景明
随机生成的阅读数是 2452
获得的当前发布时间 2020-10-31 13:15:38
运行次数统计 30
获取到的文章标题 生辰八字起名之好和罕见的宝宝名字
不存在
随机生成的作者是 越俊达
随机生成的阅读数是 3169
获得的当前发布时间 2020-10-31 13:25:41
运行次数统计 23
获取到的文章标题 自动起名 姓王的女孩有个美丽诗意的名字。
不存在
随机生成的作者是 卢俊语
随机生成的阅读数是 2471
获得的当前发布时间 2020-10-31 13:51:24
运行次数统计 18
获取到的文章标题 名字大全的杨的中性宝宝名字清单
不存在
随机生成的作者是 姚烨烁
随机生成的阅读数是 3042
获得的当前发布时间 2020-10-31 13:57:53
运行次数统计 31
获取到的文章标题 最完美的取名，罕见的宝宝名字
不存在
随机生成的作者是 步成礼
随机生成的阅读数是 3741
获得的当前发布时间 2020-10-31 14:01:13
运行次数统计 24
获取到的文章标题 免费的宝宝起名 吴姓女孩的可爱好名
不存在
随机生成的作者是 班文赋
随机生成的阅读数是 3098
获得的当前发布时间 2020-10-31 14:23:00
运行次数统计 8
获取到的文章标题 高分取名 如何给胡姓宝宝起好名字
不存在
随机生成的作者是 郗良工
随机生成的阅读数是 1187
获得的当前发布时间 2020-10-31 14:26:41
运行次数统计 9
获取到的文章标题 宝宝怎么取名，什么样的命名方法可以改善宝宝的运气
不存在
随机生成的作者是 沈嘉实
随机生成的阅读数是 1425
获得的当前发布时间 2020-10-31 14:30:45Execution of job "duoxiancheng (trigger: cron[hour='9', minute='21', second='9'], next run at: 2020-11-01 09:21:09 CST)" skipped: maximum number of running instances reached (1)
Execution of job "duoxiancheng (trigger: cron[hour='9', minute='21', second='9'], next run at: 2020-11-02 09:21:09 CST)" skipped: maximum number of running instances reached (1)
nohup: ignoring input
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
程序运行的次数 7
休眠时间 707
休眠时间 713
休眠时间 21
休眠时间 913
休眠时间 179
休眠时间 733
休眠时间 414
休眠时间 2
休眠时间 152
这个是栏目id为3 的文章长度 25
运行次数统计 1
获取到的文章标题 起名大全——漂亮的宝宝名字的完整列表
存在
运行次数统计 2
获取到的文章标题 流年起名 宝宝名字的好清单
存在
运行次数统计 3
获取到的文章标题 值得推荐的起名——漂亮优雅的宝宝名字
不存在
随机生成的作者是 程飞驰
随机生成的阅读数是 1931
获得的当前发布时间 2020-11-02 10:11:11
这个是栏目id为3 的文章长度 12
运行次数统计 1
获取到的文章标题 自动起名——如何命名康熙字典
存在
运行次数统计 2
获取到的文章标题 古诗词起名之《康熙字典》成为“命名神器”的谬论，许多学者不推荐
不存在
随机生成的作者是 燕勇军
随机生成的阅读数是 3643
获得的当前发布时间 2020-11-02 10:11:30
这个是栏目id为3 的文章长度 44
运行次数统计 1
获取到的文章标题 周易起名，如何在八月获得鼠宝宝的名字
存在
运行次数统计 2
获取到的文章标题 起名网——如何创建昵称
存在
运行次数统计 3
获取到的文章标题 起名大全之好的男宝宝名字是什么
存在
运行次数统计 4
获取到的文章标题 八字取名的如何使宝宝成为一个强大的绰号
存在
运行次数统计 5
获取到的文章标题 起名大全之坚强宝宝的完整昵称
存在
运行次数统计 6
获取到的文章标题 周易起名——很好的宝宝名字选择
不存在
随机生成的作者是 龚宏深
随机生成的阅读数是 3024
获得的当前发布时间 2020-11-02 10:13:41
这个是栏目id为3 的文章长度 111
运行次数统计 1
获取到的文章标题 科学取名的老鼠女郎有个漂亮的名字
存在
运行次数统计 2
获取到的文章标题 楚辞取名的2020年最气质的女孩名字
存在
运行次数统计 3
获取到的文章标题 小孩起名之2020年一个叫刘的老鼠女孩的好名字
存在
运行次数统计 4
获取到的文章标题 小孩起名的好仙女的名字
存在
运行次数统计 5
获取到的文章标题 好听的宝宝名字之漂亮独特且稀有的女孩名字
存在
运行次数统计 6
获取到的文章标题 周易取名之老鼠女郎的名字简单大方
存在
运行次数统计 7
获取到的文章标题 小孩起名——诗意的女孩名字
存在
运行次数统计 8
获取到的文章标题 姓名打分——女孩的文学森林系的好名字
存在
运行次数统计 9
获取到的文章标题 怎样起好名——沙棘姓氏女孩的雅致名字
存在
运行次数统计 10
获取到的文章标题 宝宝怎么取名 姓刘的女孩名字很好
存在
运行次数统计 11
获取到的文章标题 楚辞起名——杨姓女孩有一个好听的外国名字
存在
运行次数统计 12
获取到的文章标题 古诗词取名之2020年老鼠女孩的独特名字
存在
运行次数统计 13
获取到的文章标题 自动起名 姓王的女孩有个美丽诗意的名字。
存在
运行次数统计 14
获取到的文章标题 免费的宝宝起名 吴姓女孩的可爱好名
存在
运行次数统计 15
获取到的文章标题 最完美的起名之张姑娘是个俗气的名字
存在
运行次数统计 16
获取到的文章标题 免费的宝宝取名——一个姓王的女孩的简单好名字
不存在
随机生成的作者是 慕英勋
随机生成的阅读数是 2474
获得的当前发布时间 2020-11-02 10:14:10
这个是栏目id为3 的文章长度 56
运行次数统计 1
获取到的文章标题 生辰八字取名——如何使用成语给孩子起好名字
存在
运行次数统计 2
获取到的文章标题 古诗词起名的如何给宝宝起一个昵称，宝宝的昵称技巧
存在
运行次数统计 3
获取到的文章标题 楚辞起名 如何为女孩选择漂亮的单词
存在
运行次数统计 4
获取到的文章标题 宝宝怎么取名，什么样的命名方法可以改善宝宝的运气
存在
运行次数统计 5
获取到的文章标题 宝宝怎么取名的如何通过八个字符的名字知道宝宝的出生时间
存在
运行次数统计 6
获取到的文章标题 姓名打分之如何获得成功的名字
不存在
随机生成的作者是 莘庆生
随机生成的阅读数是 2406
获得的当前发布时间 2020-11-02 10:18:04
这个是栏目id为1 的文章长度 60
运行次数统计 1
获取到的文章标题 流年起名之命名宝宝的常用方法列表
存在
运行次数统计 2
获取到的文章标题 古诗词起名之命名宝宝金的关键要素
存在
运行次数统计 3
获取到的文章标题 高分取名 如何给胡姓宝宝起好名字
存在
运行次数统计 4
获取到的文章标题 古诗词起名——给梁姓宝宝命名时要注意五个要素
存在
运行次数统计 5
获取到的文章标题 免费的宝宝取名之方姓宝宝命名技巧大全
不存在
随机生成的作者是 慎宏爽
随机生成的阅读数是 1860
获得的当前发布时间 2020-11-02 10:22:56
这个是栏目id为2 的文章长度 209
运行次数统计 1
获取到的文章标题 大数据取名 猪宝宝的名字
存在
运行次数统计 2
获取到的文章标题 值得推荐的起名 猪的女宝宝名字
存在
运行次数统计 3
获取到的文章标题 楚辞起名 司马女宝宝的名字
存在
运行次数统计 4
获取到的文章标题 大数据起名，男宝宝名字
存在
运行次数统计 5
获取到的文章标题 值得推荐的起名 丁宝宝的名字
存在
运行次数统计 6
获取到的文章标题 宝宝怎么取名之女宝宝姓彭
存在
运行次数统计 7
获取到的文章标题 高分起名的三字好孩子的名字胡
存在
运行次数统计 8
获取到的文章标题 古诗词取名，胡姓好孩子的名字
存在
运行次数统计 9
获取到的文章标题 好听的宝宝名字，男宝宝名字彭
存在
运行次数统计 10
获取到的文章标题 生辰八字起名之好和罕见的宝宝名字
存在
运行次数统计 11
获取到的文章标题 最完美的取名，罕见的宝宝名字
存在
运行次数统计 12
获取到的文章标题 起名需要注意什么的新宝宝的名字
存在
运行次数统计 13
获取到的文章标题 大数据取名——宝宝名字的完整列表
存在
运行次数统计 14
获取到的文章标题 古诗词起名——诗歌和宝宝的名字
存在
运行次数统计 15
获取到的文章标题 取名网之漂亮漂亮的宝宝名字
存在
运行次数统计 16
获取到的文章标题 生辰八字取名之西式宝宝名字
存在
运行次数统计 17
获取到的文章标题 100分起名大全，宽大的宝宝名字
存在
运行次数统计 18
获取到的文章标题 姓名打分之从宋词开始给宝宝起个好名字
存在
运行次数统计 19
获取到的文章标题 新生儿起名之如何用古诗命名宝宝
存在
运行次数统计 20
获取到的文章标题 免费的宝宝起名的命名男宝宝姓氏的注意事项
存在
运行次数统计 21
获取到的文章标题 在线起名之二字羽姓男宝宝名字
存在
运行次数统计 22
获取到的文章标题 起名需要注意什么 三字俞姓男宝宝名字
不存在
随机生成的作者是 广文成
随机生成的阅读数是 1576
获得的当前发布时间 2020-11-02 10:23:09
这个是栏目id为3 的文章长度 24
运行次数统计 1
获取到的文章标题 楚辞取名之十二生肖狗的宝宝名字
存在
运行次数统计 2
获取到的文章标题 好听的宝宝名字的十二生肖的猴子的名字
不存在
随机生成的作者是 陆浩阔
随机生成的阅读数是 2629
获得的当前发布时间 2020-11-02 10:23:22
这个是栏目id为3 的文章长度 102
运行次数统计 1
获取到的文章标题 生辰八字起名，阳光明媚的男孩名字与易
存在
运行次数统计 2
获取到的文章标题 怎样取好名 那个老鼠男孩有一个英俊且举止得体的名字
存在
运行次数统计 3
获取到的文章标题 国学起名，Li骚美丽的男孩名字
存在
运行次数统计 4
获取到的文章标题 生辰八字起名——老鼠男孩有个吉祥的名字
存在
运行次数统计 5
获取到的文章标题 姓名打分 这个男孩的霸气名字叫陈
存在
运行次数统计 6
获取到的文章标题 100分起名大全——洋气，寓意男孩的名字陈
存在
运行次数统计 7
获取到的文章标题 起名需要注意什么的适合男孩用有意义的单词命名
存在
运行次数统计 8
获取到的文章标题 名字大全的杨的中性宝宝名字清单
存在
运行次数统计 9
获取到的文章标题 如何利用八字起名，刘的简单名字
存在
运行次数统计 10
获取到的文章标题 名字大全之黄姓男孩名字很好
存在
运行次数统计 11
获取到的文章标题 楚辞起名的陈的简单寓意的名字
不存在
随机生成的作者是 公承教
随机生成的阅读数是 3836
获得的当前发布时间 2020-11-02 10:26:23
运行次数统计 17
获取到的文章标题 古诗词起名——一个名叫张的女孩的好名字
不存在
随机生成的作者是 宋鸿远
随机生成的阅读数是 2468
获得的当前发布时间 2020-11-02 10:52:40
运行次数统计 12
获取到的文章标题 免费八字起名——陈姓男孩的好名字
不存在
随机生成的作者是 衡俊英
随机生成的阅读数是 1637
获得的当前发布时间 2020-11-02 10:57:43
运行次数统计 23
获取到的文章标题 姓名打分之两个字勒姓男宝宝的名字
不存在
随机生成的作者是 禄俊明
随机生成的阅读数是 1583
获得的当前发布时间 2020-11-02 10:59:36
运行次数统计 3
获取到的文章标题 取名网 十二生肖鼠的宝宝名字
不存在
随机生成的作者是 高意蕴
随机生成的阅读数是 2569
获得的当前发布时间 2020-11-02 11:06:13
运行次数统计 24
获取到的文章标题 流行的宝宝取名之三字乐姓男宝宝名字
不存在
随机生成的作者是 暴逸仙
随机生成的阅读数是 3996
获得的当前发布时间 2020-11-02 11:14:48
运行次数统计 18
获取到的文章标题 生辰八字取名的杨姓的女孩太霸气了
不存在
随机生成的作者是 屠明辉
随机生成的阅读数是 1072
获得的当前发布时间 2020-11-02 11:30:07
运行次数统计 25
获取到的文章标题 古诗词起名之张姓男宝宝二字名
不存在
随机生成的作者是 红俊智
随机生成的阅读数是 1390
获得的当前发布时间 2020-11-02 11:31:19
运行次数统计 13
获取到的文章标题 新生儿起名——徐的霸气单名
不存在
随机生成的作者是 广文成
随机生成的阅读数是 2805
获得的当前发布时间 2020-11-02 11:35:08
运行次数统计 26
获取到的文章标题 取名技巧 男宝宝的名字
不存在
随机生成的作者是 范懿轩
随机生成的阅读数是 2315
获得的当前发布时间 2020-11-02 11:47:03
运行次数统计 7
获取到的文章标题 热门起名技巧，如何根据星座来确定命运的强度
不存在
随机生成的作者是 鱼子民
随机生成的阅读数是 1805
获得的当前发布时间 2020-11-02 11:48:53
运行次数统计 6
获取到的文章标题 大数据起名——如何为有姓氏的宝宝使用诗歌
不存在
随机生成的作者是 步成礼
随机生成的阅读数是 3964
获得的当前发布时间 2020-11-02 11:52:11
运行次数统计 19
获取到的文章标题 取名技巧——缺水宝宝的名字的内涵
不存在
随机生成的作者是 贡元武
随机生成的阅读数是 3207
获得的当前发布时间 2020-11-02 12:03:53
运行次数统计 14
获取到的文章标题 流年起名 姓吴的男宝宝名字很好
不存在
随机生成的作者是 茹德元
随机生成的阅读数是 1462
获得的当前发布时间 2020-11-02 12:10:10
运行次数统计 7
获取到的文章标题 高分取名——老鼠年份的男孩名字
不存在
随机生成的作者是 蔡嘉荣
随机生成的阅读数是 3055
获得的当前发布时间 2020-11-02 12:10:37
运行次数统计 27
获取到的文章标题 生辰八字取名，男宝宝的名字
不存在
随机生成的作者是 晃高卓
随机生成的阅读数是 3897
获得的当前发布时间 2020-11-02 12:18:57
运行次数统计 28
获取到的文章标题 免费八字取名 男宝宝姓吴
不存在
随机生成的作者是 金璞玉
随机生成的阅读数是 3383
获得的当前发布时间 2020-11-02 12:39:07
运行次数统计 15
获取到的文章标题 起名网之民国时期卷轴男孩的名字
不存在
随机生成的作者是 漕弘阔
随机生成的阅读数是 1608
获得的当前发布时间 2020-11-02 12:41:57
运行次数统计 20
获取到的文章标题 姓名打分——缺水的小陈的名字
不存在
随机生成的作者是 文涵意
随机生成的阅读数是 3174
获得的当前发布时间 2020-11-02 12:45:41
运行次数统计 8
获取到的文章标题 国学起名——宝贝名字
不存在
随机生成的作者是 班文赋
随机生成的阅读数是 2099
获得的当前发布时间 2020-11-02 13:11:29
运行次数统计 16
获取到的文章标题 免费八字取名的一个有老鼠太阳姓氏的男孩
不存在
随机生成的作者是 钟成双
随机生成的阅读数是 1250
获得的当前发布时间 2020-11-02 13:18:26
运行次数统计 29
获取到的文章标题 科学的宝宝起名，好男孩名字与吴姓
不存在
随机生成的作者是 鱼浦和
随机生成的阅读数是 2429
获得的当前发布时间 2020-11-02 13:18:51
运行次数统计 21
获取到的文章标题 楚辞取名 《诗经》中杨氏宝宝命名的完整技巧
不存在
随机生成的作者是 璩烨烨
随机生成的阅读数是 3442
获得的当前发布时间 2020-11-02 13:21:33
运行次数统计 8
获取到的文章标题 大数据起名，老鼠米饭的绰号
不存在
随机生成的作者是 阴乐天
随机生成的阅读数是 2391
获得的当前发布时间 2020-11-02 13:28:27
运行次数统计 7
获取到的文章标题 起名技巧的如何给一个姓石的宝宝命名
不存在
随机生成的作者是 符乐山
随机生成的阅读数是 2031
获得的当前发布时间 2020-11-02 13:34:24
运行次数统计 4
获取到的文章标题 生辰八字取名的具有特殊含义的宝宝名字的完整列表
不存在
随机生成的作者是 姜俊雄
随机生成的阅读数是 2967
获得的当前发布时间 2020-11-02 13:36:29
运行次数统计 22
获取到的文章标题 流行的宝宝取名——诗经中的气质女孩名字列表
不存在
随机生成的作者是 向景铄
随机生成的阅读数是 1420
获得的当前发布时间 2020-11-02 13:55:40
运行次数统计 30
获取到的文章标题 科学起名之女宝宝命名注意事项
不存在
随机生成的作者是 戈鸿光
随机生成的阅读数是 2615
获得的当前发布时间 2020-11-02 13:58:43
运行次数统计 17
获取到的文章标题 小孩起名 好男孩名字“hao”
不存在
随机生成的作者是 易成天
随机生成的阅读数是 2809
获得的当前发布时间 2020-11-02 13:59:53
运行次数统计 9
获取到的文章标题 小孩起名的具有最高容错能力的命名技巧百科全书
不存在
随机生成的作者是 李金鑫
随机生成的阅读数是 3091
获得的当前发布时间 2020-11-02 14:22:47
运行次数统计 23
获取到的文章标题 科学取名的如何给黄姓女孩取一个寓意的名字
不存在
随机生成的作者是 秦明远
随机生成的阅读数是 3858
获得的当前发布时间 2020-11-02 14:31:48
运行次数统计 31
获取到的文章标题 免费八字取名，女宝宝名字
不存在
随机生成的作者是 汲阳泽
随机生成的阅读数是 1293
获得的当前发布时间 2020-11-02 14:33:45
运行次数统计 18
获取到的文章标题 古诗词起名 鼠年帅哥叫吴
不存在
随机生成的作者是 史鸿雪
随机生成的阅读数是Job "duoxiancheng (trigger: cron[hour='10', minute='11', second='9'], next run at: 2020-11-03 10:11:09 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 713, in _write_bytes
    self._sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 771, in _execute_command
    self._write_bytes(packet)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 718, in _write_bytes
    "MySQL server has gone away (%r)" % (e,))
pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "fabu0923.py", line 509, in duoxiancheng
    db.session.commit()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2523, in flush
    self._flush(objects)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2624, in _flush
    flush_context.execute()
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    statement, params
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1133, in _execute_clauseelement
    distilled_params,
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1318, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1512, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/python3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 771, in _execute_command
    self._write_bytes(packet)
  File "/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py", line 718, in _write_bytes
    "MySQL server has gone away (%r)" % (e,))
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
[SQL: INSERT INTO cishu (cishu) VALUES (%(cishu)s)]
[parameters: {'cishu': 6}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
 2189
获得的当前发布时间 2020-11-02 14:40:11
运行次数统计 9
获取到的文章标题 古诗词起名的鼠宝宝男孩是个好绰号
不存在
随机生成的作者是 曾文赋
随机生成的阅读数是 2660
获得的当前发布时间 2020-11-02 14:52:19
运行次数统计 24
获取到的文章标题 新生儿起名，内涵和独特的宝宝名字黄
不存在
随机生成的作者是 茹德元
随机生成的阅读数是 3977
获得的当前发布时间 2020-11-02 15:04:23
运行次数统计 8
获取到的文章标题 流行的宝宝取名——姓何的宝宝
不存在
随机生成的作者是 邰祺瑞
随机生成的阅读数是 1337
获得的当前发布时间 2020-11-02 15:11:49
运行次数统计 19
获取到的文章标题 大数据取名，老鼠年的独特和稀有男孩名字
不存在
随机生成的作者是 乜弘新
随机生成的阅读数是 3947
获得的当前发布时间 2020-11-02 15:15:00
运行次数统计 32
获取到的文章标题 大数据起名 女宝宝命名注意事项
不存在
随机生成的作者是 侯志学
随机生成的阅读数是 2235
获得的当前发布时间 2020-11-02 15:17:54
运行次数统计 33
获取到的文章标题 免费八字起名 宝贝女孩的名字
不存在
随机生成的作者是 鱼刚毅
随机生成的阅读数是 3585
获得的当前发布时间 2020-11-02 15:37:00
运行次数统计 25
获取到的文章标题 起名网 女宝宝的庄严和寓意的名字
不存在
随机生成的作者是 牛健柏
随机生成的阅读数是 3068
获得的当前发布时间 2020-11-02 15:47:04
运行次数统计 10
获取到的文章标题 在线起名——可以给孩子带来好运的名字的完整列表
不存在
随机生成的作者是 暴阳平
随机生成的阅读数是 1443
获得的当前发布时间 2020-11-02 15:52:09
运行次数统计 20
获取到的文章标题 楚辞取名，王某姓大气的男孩
不存在
随机生成的作者是 从元纬
随机生成的阅读数是 2759
获得的当前发布时间 2020-11-02 15:52:34
运行次数统计 34
获取到的文章标题 如何利用八字起名之两个字符的好听的男孩名字王
不存在
随机生成的作者是 索永福
随机生成的阅读数是 1461
获得的当前发布时间 2020-11-02 16:01:17
运行次数统计 35
获取到的文章标题 在线起名 好男孩名字与王姓
不存在
随机生成的作者是 杨风华
随机生成的阅读数是 3028
获得的当前发布时间 2020-11-02 16:20:00
运行次数统计 10
获取到的文章标题 姓名打分，鼠年里男孩的创意名字
不存在
随机生成的作者是 汲阳泽
随机生成的阅读数是 3771
获得的当前发布时间 2020-11-02 16:21:41
运行次数统计 9
获取到的文章标题 最完美的起名之冯的宝贝名字
不存在
随机生成的作者是 桓阳煦
随机生成的阅读数是 3258
获得的当前发布时间 2020-11-02 16:38:12
运行次数统计 36
获取到的文章标题 科学起名的单个字符听起来不错
不存在
随机生成的作者是 唐安国
随机生成的阅读数是 1915
获得的当前发布时间 2020-11-02 16:51:15
运行次数统计 37
获取到的文章标题 免费八字取名之好孩子的名字宁
不存在
随机生成的作者是 梁彬郁
随机生成的阅读数是 2038
获得的当前发布时间 2020-11-02 17:31:09
运行次数统计 38
获取到的文章标题 名字大全之猪年好听的韩姓女孩名字
不存在
随机生成的作者是 谭皓轩
随机生成的阅读数是 1866
获得的当前发布时间 2020-11-02 18:00:06
运行次数统计 39
获取到的文章标题 新生儿起名的最新猪年宁姓宝宝名字大全
不存在
随机生成的作者是 毋修竹
随机生成的阅读数是 3999
获得的当前发布时间 2020-11-02 18:32:31
运行次数统计 40
获取到的文章标题 起名技巧的曹姓男孩起名字大全
不存在
随机生成的作者是 劳华灿
随机生成的阅读数是 1713
获得的当前发布时间 2020-11-02 19:07:53
运行次数统计 41
获取到的文章标题 起名网之很高兴听到宝宝的名字徐
不存在
随机生成的作者是 沈嘉实
随机生成的阅读数是 2216
获得的当前发布时间 2020-11-02 19:47:17
主线程结束
程序运行的次数 7
休眠时间 329
休眠时间 434
休眠时间 658
休眠时间 49
休眠时间 211
休眠时间 397
休眠时间 795
休眠时间 934
休眠时间 356
这个是栏目id为3 的文章长度 112
运行次数统计 1
获取到的文章标题 楚辞起名的陈的简单寓意的名字
存在
运行次数统计 2
获取到的文章标题 免费八字起名——陈姓男孩的好名字
存在
运行次数统计 3
获取到的文章标题 新生儿起名——徐的霸气单名
存在
运行次数统计 4
获取到的文章标题 流年起名 姓吴的男宝宝名字很好
存在
运行次数统计 5
获取到的文章标题 起名网之民国时期卷轴男孩的名字
存在
运行次数统计 6
获取到的文章标题 免费八字取名的一个有老鼠太阳姓氏的男孩
存在
运行次数统计 7
获取到的文章标题 小孩起名 好男孩名字“hao”
存在
运行次数统计 8
获取到的文章标题 古诗词起名 鼠年帅哥叫吴
存在
运行次数统计 9
获取到的文章标题 大数据取名，老鼠年的独特和稀有男孩名字
存在
运行次数统计 10
获取到的文章标题 楚辞取名，王某姓大气的男孩
存在
运行次数统计 11
获取到的文章标题 新生儿如何起名，鼠年里唯一和罕见的男孩名字
不存在
随机生成的作者是 易俊杰
随机生成的阅读数是 2732
获得的当前发布时间 2020-11-03 10:11:59
这个是栏目id为3 的文章长度 121
运行次数统计 1
获取到的文章标题 楚辞起名——杨姓女孩有一个好听的外国名字
存在
运行次数统计 2
获取到的文章标题 古诗词取名之2020年老鼠女孩的独特名字
存在
运行次数统计 3
获取到的文章标题 自动起名 姓王的女孩有个美丽诗意的名字。
存在
运行次数统计 4
获取到的文章标题 免费的宝宝起名 吴姓女孩的可爱好名
存在
运行次数统计 5
获取到的文章标题 最完美的起名之张姑娘是个俗气的名字
存在
运行次数统计 6
获取到的文章标题 免费的宝宝取名——一个姓王的女孩的简单好名字
存在
运行次数统计 7
获取到的文章标题 古诗词起名——一个名叫张的女孩的好名字
存在
运行次数统计 8
获取到的文章标题 生辰八字取名的杨姓的女孩太霸气了
存在
运行次数统计 9
获取到的文章标题 取名技巧——缺水宝宝的名字的内涵
存在
运行次数统计 10
获取到的文章标题 姓名打分——缺水的小陈的名字
存在
运行次数统计 11
获取到的文章标题 楚辞取名 《诗经》中杨氏宝宝命名的完整技巧
存在
运行次数统计 12
获取到的文章标题 流行的宝宝取名——诗经中的气质女孩名字列表
存在
运行次数统计 13
获取到的文章标题 科学取名的如何给黄姓女孩取一个寓意的名字
存在
运行次数统计 14
获取到的文章标题 新生儿起名，内涵和独特的宝宝名字黄
存在
运行次数统计 15
获取到的文章标题 起名网 女宝宝的庄严和寓意的名字
存在
运行次数统计 16
获取到的文章标题 起名大全——徐姓女宝宝的好名字是什么
不存在
随机生成的作者是 蒙宏邈
随机生成的阅读数是 3959
获得的当前发布时间 2020-11-03 10:14:42
这个是栏目id为1 的文章长度 65
运行次数统计 1
获取到的文章标题 大数据起名——如何为有姓氏的宝宝使用诗歌
存在
运行次数统计 2
获取到的文章标题 起名技巧的如何给一个姓石的宝宝命名
存在
运行次数统计 3
获取到的文章标题 流行的宝宝取名——姓何的宝宝
存在
运行次数统计 4
获取到的文章标题 最完美的起名之冯的宝贝名字
存在
运行次数统计 5
获取到的文章标题 自动起名的田的宝宝名字
不存在
随机生成的作者是 满德曜
随机生成的阅读数是 1766
获得的当前发布时间 2020-11-03 10:16:38
这个是栏目id为3 的文章长度 49
运行次数统计 1
获取到的文章标题 周易起名——很好的宝宝名字选择
存在
运行次数统计 2
获取到的文章标题 高分取名——老鼠年份的男孩名字
存在
运行次数统计 3
获取到的文章标题 大数据起名，老鼠米饭的绰号
存在
运行次数统计 4
获取到的文章标题 古诗词起名的鼠宝宝男孩是个好绰号
存在
运行次数统计 5
获取到的文章标题 姓名打分，鼠年里男孩的创意名字
存在
运行次数统计 6
获取到的文章标题 起名网，简单易记的女孩昵称
不存在
随机生成的作者是 满德曜
随机生成的阅读数是 3136
获得的当前发布时间 2020-11-03 10:17:05
这个是栏目id为3 的文章长度 26
运行次数统计 1
获取到的文章标题 取名网 十二生肖鼠的宝宝名字
存在
运行次数统计 2
获取到的文章标题 古诗词取名 生肖龙宝宝的名字
不存在
随机生成的作者是 蒲咏志
随机生成的阅读数是 3579
获得的当前发布时间 2020-11-03 10:17:46
这个是栏目id为2 的文章长度 229
运行次数统计 1
获取到的文章标题 在线起名之二字羽姓男宝宝名字
存在
运行次数统计 2
获取到的文章标题 起名需要注意什么 三字俞姓男宝宝名字
存在
运行次数统计 3
获取到的文章标题 姓名打分之两个字勒姓男宝宝的名字
存在
运行次数统计 4
获取到的文章标题 流行的宝宝取名之三字乐姓男宝宝名字
存在
运行次数统计 5
获取到的文章标题 古诗词起名之张姓男宝宝二字名
存在
运行次数统计 6
获取到的文章标题 取名技巧 男宝宝的名字
存在
运行次数统计 7
获取到的文章标题 生辰八字取名，男宝宝的名字
存在
运行次数统计 8
获取到的文章标题 免费八字取名 男宝宝姓吴
存在
运行次数统计 9
获取到的文章标题 科学的宝宝起名，好男孩名字与吴姓
存在
运行次数统计 10
获取到的文章标题 科学起名之女宝宝命名注意事项
存在
运行次数统计 11
获取到的文章标题 免费八字取名，女宝宝名字
存在
运行次数统计 12
获取到的文章标题 大数据起名 女宝宝命名注意事项
存在
运行次数统计 13
获取到的文章标题 免费八字起名 宝贝女孩的名字
存在
运行次数统计 14
获取到的文章标题 如何利用八字起名之两个字符的好听的男孩名字王
存在
运行次数统计 15
获取到的文章标题 在线起名 好男孩名字与王姓
存在
运行次数统计 16
获取到的文章标题 科学起名的单个字符听起来不错
存在
运行次数统计 17
获取到的文章标题 免费八字取名之好孩子的名字宁
存在
运行次数统计 18
获取到的文章标题 名字大全之猪年好听的韩姓女孩名字
存在
运行次数统计 19
获取到的文章标题 新生儿起名的最新猪年宁姓宝宝名字大全
存在
运行次数统计 20
获取到的文章标题 起名技巧的曹姓男孩起名字大全
存在
运行次数统计 21
获取到的文章标题 起名网之很高兴听到宝宝的名字徐
存在
运行次数统计 22
获取到的文章标题 周易起名 含Hu的寓意女孩名字
不存在
随机生成的作者是 孙兴学
随机生成的阅读数是 1239
获得的当前发布时间 2020-11-03 10:18:33
这个是栏目id为3 的文章长度 13
运行次数统计 1
获取到的文章标题 古诗词起名之《康熙字典》成为“命名神器”的谬论，许多学者不推荐
存在
运行次数统计 2
获取到的文章标题 好听的宝宝名字的二十七绘字
不存在
随机生成的作者是 訾玉龙
随机生成的阅读数是 1235
获得的当前发布时间 2020-11-03 10:22:07
这个是栏目id为3 的文章长度 61
运行次数统计 1
获取到的文章标题 姓名打分之如何获得成功的名字
存在
运行次数统计 2
获取到的文章标题 热门起名技巧，如何根据星座来确定命运的强度
存在
运行次数统计 3
获取到的文章标题 国学起名——宝贝名字
存在
运行次数统计 4
获取到的文章标题 小孩起名的具有最高容错能力的命名技巧百科全书
存在
运行次数统计 5
获取到的文章标题 在线起名——可以给孩子带来好运的名字的完整列表
存在
运行次数统计 6
获取到的文章标题 取名网的乐观的人的名字叫多少笔
不存在
随机生成的作者是 菱新觉
随机生成的阅读数是 2888
获得的当前发布时间 2020-11-03 10:24:25
这个是栏目id为3 的文章长度 27
运行次数统计 1
获取到的文章标题 值得推荐的起名——漂亮优雅的宝宝名字
存在
运行次数统计 2
获取到的文章标题 生辰八字取名的具有特殊含义的宝宝名字的完整列表
存在
运行次数统计 3
获取到的文章标题 科学起名，幼鼠名字的完整列表
不存在
随机生成的作者是 阙浩博
随机生成的阅读数是 3188
获得的当前发布时间 2020-11-03 10:26:44
运行次数统计 17
获取到的文章标题 流行的宝宝取名——黄姓的女宝宝
不存在
随机生成的作者是 沃彬彬
随机生成的阅读数是 3796
获得的当前发布时间 2020-11-03 10:44:52
运行次数统计 3
获取到的文章标题 楚辞取名的十二生肖蛇宝宝的名字
不存在
随机生成的作者是 邴阳云
随机生成的阅读数是 3219
获得的当前发布时间 2020-11-03 10:48:01
运行次数统计 12
获取到的文章标题 起名网的温柔优雅的男孩名字
不存在
随机生成的作者是 寇锐精
随机生成的阅读数是 2688
获得的当前发布时间 2020-11-03 10:55:24
运行次数统计 23
获取到的文章标题 高分取名的叫霍的女孩名字很简单
不存在
随机生成的作者是 曾文赋
随机生成的阅读数是 3870
获得的当前发布时间 2020-11-03 11:01:17
运行次数统计 24
获取到的文章标题 免费的宝宝取名之两个字母的女孩名字，姓霍
不存在
随机生成的作者是 惠永春
随机生成的阅读数是 2292
获得的当前发布时间 2020-11-03 11:24:27
运行次数统计 18
获取到的文章标题 小孩取名之好评的赵小宝贝
不存在
随机生成的作者是 家敏学
随机生成的阅读数是 2613
获得的当前发布时间 2020-11-03 11:28:37
运行次数统计 13
获取到的文章标题 古诗词起名，男孩的吉祥名字
不存在
随机生成的作者是 林阳秋
随机生成的阅读数是 2422
获得的当前发布时间 2020-11-03 11:33:54
运行次数统计 7
获取到的文章标题 起名技巧——鼠年
不存在
随机生成的作者是 庾高澹
随机生成的阅读数是 1917
获得的当前发布时间 2020-11-03 11:41:42
运行次数统计 4
获取到的文章标题 好听的宝宝名字的宝贝名字
不存在
随机生成的作者是 赵元甲
随机生成的阅读数是 3851
获得的当前发布时间 2020-11-03 11:49:15
运行次数统计 7
获取到的文章标题 科学取名的当五个要素缺水时如何命名宝宝
不存在
随机生成的作者是 姚阳伯
随机生成的阅读数是 2942
获得的当前发布时间 2020-11-03 11:52:53
运行次数统计 25
获取到的文章标题 国学起名——单字符霍女孩的名字
不存在
随机生成的作者是 盖嘉颖
随机生成的阅读数是 3801
获得的当前发布时间 2020-11-03 11:57:30
运行次数统计 6
获取到的文章标题 姓名打分之宝宝的名字清单
不存在
随机生成的作者是 蒙宏邈
随机生成的阅读数是 1709
获得的当前发布时间 2020-11-03 12:04:22
运行次数统计 19
获取到的文章标题 流年起名——周姓女孩的名字优雅而含蓄
不存在
随机生成的作者是 步宏爽
随机生成的阅读数是 2290
获得的当前发布时间 2020-11-03 12:06:22
运行次数统计 14
获取到的文章标题 流行的宝宝取名 2020年老鼠的有意义的男孩名字
不存在
随机生成的作者是 姚鸿羲
随机生成的阅读数是 1360
获得的当前发布时间 2020-11-03 12:16:13